part of 'gen_fonts.dart';

_add_fonts_linux(Map<String, List<(String, FontStyle, FontWeight)>> fonts) {
  fonts["linux"] = [
    ('Noto Sans Brahmi', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Brahmi', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Brahmi', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Brahmi', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Tamil', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Tamil', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Tamil', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Tamil', FontStyle.normal, FontWeight.bold),
    ('Noto Serif Devanagari', FontStyle.normal, FontWeight.normal),
    ('Noto Serif Devanagari', FontStyle.italic, FontWeight.normal),
    ('Noto Serif Devanagari', FontStyle.italic, FontWeight.bold),
    ('Noto Serif Devanagari', FontStyle.normal, FontWeight.bold),
    ('Inter', FontStyle.normal, FontWeight.normal),
    ('Inter', FontStyle.normal, FontWeight.bold),
    ('Inter', FontStyle.italic, FontWeight.normal),
    ('Inter', FontStyle.italic, FontWeight.bold),
    ('Noto Serif Thai', FontStyle.normal, FontWeight.normal),
    ('Noto Serif Thai', FontStyle.italic, FontWeight.normal),
    ('Noto Serif Thai', FontStyle.italic, FontWeight.bold),
    ('Noto Serif Thai', FontStyle.normal, FontWeight.bold),
    ('Noto Looped Thai', FontStyle.normal, FontWeight.normal),
    ('Noto Looped Thai', FontStyle.italic, FontWeight.normal),
    ('Noto Looped Thai', FontStyle.italic, FontWeight.bold),
    ('Noto Looped Thai', FontStyle.normal, FontWeight.bold),
    ('Noto Serif Hebrew', FontStyle.normal, FontWeight.normal),
    ('Noto Serif Hebrew', FontStyle.italic, FontWeight.normal),
    ('Noto Serif Hebrew', FontStyle.italic, FontWeight.bold),
    ('Noto Serif Hebrew', FontStyle.normal, FontWeight.bold),
    ('Noto Serif Ahom', FontStyle.normal, FontWeight.normal),
    ('Noto Serif Ahom', FontStyle.italic, FontWeight.normal),
    ('Noto Serif Ahom', FontStyle.normal, FontWeight.bold),
    ('Noto Serif Ahom', FontStyle.italic, FontWeight.bold),
    ('Noto Sans', FontStyle.normal, FontWeight.normal),
    ('Noto Sans', FontStyle.normal, FontWeight.bold),
    ('Noto Sans', FontStyle.italic, FontWeight.normal),
    ('Noto Sans', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Hebrew', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Hebrew', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Hebrew', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Hebrew', FontStyle.normal, FontWeight.bold),
    ('Ubuntu Sans', FontStyle.normal, FontWeight.normal),
    ('Ubuntu Sans', FontStyle.normal, FontWeight.bold),
    ('Ubuntu Sans', FontStyle.italic, FontWeight.normal),
    ('Ubuntu Sans', FontStyle.italic, FontWeight.bold),
    ('Noto Serif Khmer', FontStyle.normal, FontWeight.normal),
    ('Noto Serif Khmer', FontStyle.italic, FontWeight.normal),
    ('Noto Serif Khmer', FontStyle.italic, FontWeight.bold),
    ('Noto Serif Khmer', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Armenian', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Armenian', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Armenian', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Armenian', FontStyle.normal, FontWeight.bold),
    ('Noto Sans CJK SC', FontStyle.normal, FontWeight.normal),
    ('Noto Sans CJK SC', FontStyle.italic, FontWeight.normal),
    ('Noto Sans CJK SC', FontStyle.italic, FontWeight.bold),
    ('Noto Sans CJK SC', FontStyle.normal, FontWeight.bold),
    ('Noto Sans CJK KR', FontStyle.normal, FontWeight.normal),
    ('Noto Sans CJK KR', FontStyle.italic, FontWeight.normal),
    ('Noto Sans CJK KR', FontStyle.italic, FontWeight.bold),
    ('Noto Sans CJK KR', FontStyle.normal, FontWeight.bold),
    ('Noto Sans CJK HK', FontStyle.normal, FontWeight.normal),
    ('Noto Sans CJK HK', FontStyle.italic, FontWeight.normal),
    ('Noto Sans CJK HK', FontStyle.italic, FontWeight.bold),
    ('Noto Sans CJK HK', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Sinhala', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Sinhala', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Sinhala', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Sinhala', FontStyle.normal, FontWeight.bold),
    ('Noto Sans CJK JP', FontStyle.normal, FontWeight.normal),
    ('Noto Sans CJK JP', FontStyle.italic, FontWeight.normal),
    ('Noto Sans CJK JP', FontStyle.italic, FontWeight.bold),
    ('Noto Sans CJK JP', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Thai', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Thai', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Thai', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Thai', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Canadian Aboriginal', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Canadian Aboriginal', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Canadian Aboriginal', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Canadian Aboriginal', FontStyle.normal, FontWeight.bold),
    ('Noto Serif', FontStyle.normal, FontWeight.normal),
    ('Noto Serif', FontStyle.normal, FontWeight.bold),
    ('Noto Serif', FontStyle.italic, FontWeight.normal),
    ('Noto Serif', FontStyle.italic, FontWeight.bold),
    ('Cantarell', FontStyle.normal, FontWeight.normal),
    ('Cantarell', FontStyle.italic, FontWeight.normal),
    ('Cantarell', FontStyle.italic, FontWeight.bold),
    ('Cantarell', FontStyle.normal, FontWeight.bold),
    ('Noto Sans CJK TC', FontStyle.normal, FontWeight.normal),
    ('Noto Sans CJK TC', FontStyle.italic, FontWeight.normal),
    ('Noto Sans CJK TC', FontStyle.italic, FontWeight.bold),
    ('Noto Sans CJK TC', FontStyle.normal, FontWeight.bold),
    ('Noto Serif Tamil Slanted', FontStyle.normal, FontWeight.normal),
    ('Noto Serif Tamil Slanted', FontStyle.italic, FontWeight.normal),
    ('Noto Serif Tamil Slanted', FontStyle.italic, FontWeight.bold),
    ('Noto Serif Tamil Slanted', FontStyle.normal, FontWeight.bold),
    ('Georgia', FontStyle.normal, FontWeight.normal),
    ('Georgia', FontStyle.normal, FontWeight.bold),
    ('Georgia', FontStyle.italic, FontWeight.normal),
    ('Georgia', FontStyle.italic, FontWeight.bold),
    ('Roboto Condensed', FontStyle.normal, FontWeight.normal),
    ('Roboto Condensed', FontStyle.normal, FontWeight.bold),
    ('Roboto Condensed', FontStyle.italic, FontWeight.normal),
    ('Roboto Condensed', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Telugu', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Telugu', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Telugu', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Telugu', FontStyle.normal, FontWeight.bold),
    ('Noto Serif Armenian', FontStyle.normal, FontWeight.normal),
    ('Noto Serif Armenian', FontStyle.italic, FontWeight.normal),
    ('Noto Serif Armenian', FontStyle.italic, FontWeight.bold),
    ('Noto Serif Armenian', FontStyle.normal, FontWeight.bold),
    ('Noto Serif Sinhala', FontStyle.normal, FontWeight.normal),
    ('Noto Serif Sinhala', FontStyle.italic, FontWeight.normal),
    ('Noto Serif Sinhala', FontStyle.italic, FontWeight.bold),
    ('Noto Serif Sinhala', FontStyle.normal, FontWeight.bold),
    ('Noto Serif Display', FontStyle.normal, FontWeight.normal),
    ('Noto Serif Display', FontStyle.normal, FontWeight.bold),
    ('Noto Serif Display', FontStyle.italic, FontWeight.normal),
    ('Noto Serif Display', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Nabataean', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Nabataean', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Nabataean', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Nabataean', FontStyle.italic, FontWeight.bold),
    ('Noto Serif Georgian', FontStyle.normal, FontWeight.normal),
    ('Noto Serif Georgian', FontStyle.italic, FontWeight.normal),
    ('Noto Serif Georgian', FontStyle.italic, FontWeight.bold),
    ('Noto Serif Georgian', FontStyle.normal, FontWeight.bold),
    ('Lato', FontStyle.normal, FontWeight.normal),
    ('Lato', FontStyle.normal, FontWeight.bold),
    ('Lato', FontStyle.italic, FontWeight.normal),
    ('Lato', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Malayalam', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Malayalam', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Malayalam', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Malayalam', FontStyle.normal, FontWeight.bold),
    ('Noto Serif Tamil', FontStyle.normal, FontWeight.normal),
    ('Noto Serif Tamil', FontStyle.italic, FontWeight.normal),
    ('Noto Serif Tamil', FontStyle.italic, FontWeight.bold),
    ('Noto Serif Tamil', FontStyle.normal, FontWeight.bold),
    ('Noto Serif Gurmukhi', FontStyle.normal, FontWeight.normal),
    ('Noto Serif Gurmukhi', FontStyle.italic, FontWeight.normal),
    ('Noto Serif Gurmukhi', FontStyle.italic, FontWeight.bold),
    ('Noto Serif Gurmukhi', FontStyle.normal, FontWeight.bold),
    ('Noto Looped Lao', FontStyle.normal, FontWeight.normal),
    ('Noto Looped Lao', FontStyle.italic, FontWeight.normal),
    ('Noto Looped Lao', FontStyle.italic, FontWeight.bold),
    ('Noto Looped Lao', FontStyle.normal, FontWeight.bold),
    ('Linux Libertine Display O', FontStyle.normal, FontWeight.normal),
    ('Linux Libertine Display O', FontStyle.italic, FontWeight.normal),
    ('Linux Libertine Display O', FontStyle.normal, FontWeight.bold),
    ('Linux Libertine Display O', FontStyle.italic, FontWeight.bold),
    ('Times New Roman', FontStyle.normal, FontWeight.normal),
    ('Times New Roman', FontStyle.normal, FontWeight.bold),
    ('Times New Roman', FontStyle.italic, FontWeight.normal),
    ('Times New Roman', FontStyle.italic, FontWeight.bold),
    ('Noto Serif Myanmar', FontStyle.normal, FontWeight.normal),
    ('Noto Serif Myanmar', FontStyle.italic, FontWeight.normal),
    ('Noto Serif Myanmar', FontStyle.italic, FontWeight.bold),
    ('Noto Serif Myanmar', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Osmanya', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Osmanya', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Osmanya', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Osmanya', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Kayah Li', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Kayah Li', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Kayah Li', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Kayah Li', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Khmer', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Khmer', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Khmer', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Khmer', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Sundanese', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Sundanese', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Sundanese', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Sundanese', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Cham', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Cham', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Cham', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Cham', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Ugaritic', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Ugaritic', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Ugaritic', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Ugaritic', FontStyle.italic, FontWeight.bold),
    ('Noto Naskh Arabic', FontStyle.normal, FontWeight.normal),
    ('Noto Naskh Arabic', FontStyle.italic, FontWeight.normal),
    ('Noto Naskh Arabic', FontStyle.italic, FontWeight.bold),
    ('Noto Naskh Arabic', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Devanagari', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Devanagari', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Devanagari', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Devanagari', FontStyle.normal, FontWeight.bold),
    ('Noto Serif Bengali', FontStyle.normal, FontWeight.normal),
    ('Noto Serif Bengali', FontStyle.italic, FontWeight.normal),
    ('Noto Serif Bengali', FontStyle.italic, FontWeight.bold),
    ('Noto Serif Bengali', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Arabic', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Arabic', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Arabic', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Arabic', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Display', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Display', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Display', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Display', FontStyle.italic, FontWeight.bold),
    ('Noto Sans New Tai Lue', FontStyle.normal, FontWeight.normal),
    ('Noto Sans New Tai Lue', FontStyle.italic, FontWeight.normal),
    ('Noto Sans New Tai Lue', FontStyle.normal, FontWeight.bold),
    ('Noto Sans New Tai Lue', FontStyle.italic, FontWeight.bold),
    ('Noto Serif Khojki', FontStyle.normal, FontWeight.normal),
    ('Noto Serif Khojki', FontStyle.italic, FontWeight.normal),
    ('Noto Serif Khojki', FontStyle.italic, FontWeight.bold),
    ('Noto Serif Khojki', FontStyle.normal, FontWeight.bold),
    ('Ubuntu Sans Mono', FontStyle.normal, FontWeight.normal),
    ('Ubuntu Sans Mono', FontStyle.normal, FontWeight.bold),
    ('Ubuntu Sans Mono', FontStyle.italic, FontWeight.normal),
    ('Ubuntu Sans Mono', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Lao', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Lao', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Lao', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Lao', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Thaana', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Thaana', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Thaana', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Thaana', FontStyle.normal, FontWeight.bold),
    ('Noto Serif Kannada', FontStyle.normal, FontWeight.normal),
    ('Noto Serif Kannada', FontStyle.italic, FontWeight.normal),
    ('Noto Serif Kannada', FontStyle.italic, FontWeight.bold),
    ('Noto Serif Kannada', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Gujarati', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Gujarati', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Gujarati', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Gujarati', FontStyle.normal, FontWeight.bold),
    ('Noto Serif Ethiopic', FontStyle.normal, FontWeight.normal),
    ('Noto Serif Ethiopic', FontStyle.italic, FontWeight.normal),
    ('Noto Serif Ethiopic', FontStyle.italic, FontWeight.bold),
    ('Noto Serif Ethiopic', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Myanmar', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Myanmar', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Myanmar', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Myanmar', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Mono CJK SC', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Mono CJK SC', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Mono CJK SC', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Mono CJK SC', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Ethiopic', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Ethiopic', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Ethiopic', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Ethiopic', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Mono CJK TC', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Mono CJK TC', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Mono CJK TC', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Mono CJK TC', FontStyle.normal, FontWeight.bold),
    ('Noto Serif Tibetan', FontStyle.normal, FontWeight.normal),
    ('Noto Serif Tibetan', FontStyle.italic, FontWeight.normal),
    ('Noto Serif Tibetan', FontStyle.italic, FontWeight.bold),
    ('Noto Serif Tibetan', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Mono CJK JP', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Mono CJK JP', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Mono CJK JP', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Mono CJK JP', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Mono CJK KR', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Mono CJK KR', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Mono CJK KR', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Mono CJK KR', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Mono CJK HK', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Mono CJK HK', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Mono CJK HK', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Mono CJK HK', FontStyle.normal, FontWeight.bold),
    ('Noto Serif Lao', FontStyle.normal, FontWeight.normal),
    ('Noto Serif Lao', FontStyle.italic, FontWeight.normal),
    ('Noto Serif Lao', FontStyle.italic, FontWeight.bold),
    ('Noto Serif Lao', FontStyle.normal, FontWeight.bold),
    ('Linux Libertine O', FontStyle.normal, FontWeight.normal),
    ('Linux Libertine O', FontStyle.normal, FontWeight.bold),
    ('Linux Libertine O', FontStyle.italic, FontWeight.normal),
    ('Linux Libertine O', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Manichaean', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Manichaean', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Manichaean', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Manichaean', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Cherokee', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Cherokee', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Cherokee', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Cherokee', FontStyle.normal, FontWeight.bold),
    ('JetBrains Mono', FontStyle.normal, FontWeight.normal),
    ('JetBrains Mono', FontStyle.normal, FontWeight.bold),
    ('JetBrains Mono', FontStyle.italic, FontWeight.normal),
    ('JetBrains Mono', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Warang Citi', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Warang Citi', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Warang Citi', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Warang Citi', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Georgian', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Georgian', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Georgian', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Georgian', FontStyle.normal, FontWeight.bold),
    ('DejaVu Sans Mono', FontStyle.normal, FontWeight.normal),
    ('DejaVu Sans Mono', FontStyle.normal, FontWeight.bold),
    ('DejaVu Sans Mono', FontStyle.normal, FontWeight.normal),
    ('DejaVu Sans Mono', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Tifinagh Ahaggar', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Tifinagh Ahaggar', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Tifinagh Ahaggar', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Tifinagh Ahaggar', FontStyle.italic, FontWeight.bold),
    ('Noto Serif Malayalam', FontStyle.normal, FontWeight.normal),
    ('Noto Serif Malayalam', FontStyle.italic, FontWeight.normal),
    ('Noto Serif Malayalam', FontStyle.italic, FontWeight.bold),
    ('Noto Serif Malayalam', FontStyle.normal, FontWeight.bold),
    ('Roboto', FontStyle.normal, FontWeight.normal),
    ('Roboto', FontStyle.normal, FontWeight.bold),
    ('Roboto', FontStyle.italic, FontWeight.normal),
    ('Roboto', FontStyle.italic, FontWeight.bold),
    ('Noto Serif Yezidi', FontStyle.normal, FontWeight.normal),
    ('Noto Serif Yezidi', FontStyle.italic, FontWeight.normal),
    ('Noto Serif Yezidi', FontStyle.italic, FontWeight.bold),
    ('Noto Serif Yezidi', FontStyle.normal, FontWeight.bold),
    ('Noto Serif Telugu', FontStyle.normal, FontWeight.normal),
    ('Noto Serif Telugu', FontStyle.italic, FontWeight.normal),
    ('Noto Serif Telugu', FontStyle.italic, FontWeight.bold),
    ('Noto Serif Telugu', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Balinese', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Balinese', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Balinese', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Balinese', FontStyle.normal, FontWeight.bold),
    ('Ubuntu', FontStyle.normal, FontWeight.normal),
    ('Ubuntu', FontStyle.normal, FontWeight.bold),
    ('Ubuntu', FontStyle.italic, FontWeight.normal),
    ('Ubuntu', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Kannada', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Kannada', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Kannada', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Kannada', FontStyle.normal, FontWeight.bold),
    ('Inter Display', FontStyle.normal, FontWeight.normal),
    ('Inter Display', FontStyle.normal, FontWeight.bold),
    ('Inter Display', FontStyle.italic, FontWeight.normal),
    ('Inter Display', FontStyle.italic, FontWeight.bold),
    ('Noto Rashi Hebrew', FontStyle.normal, FontWeight.normal),
    ('Noto Rashi Hebrew', FontStyle.italic, FontWeight.normal),
    ('Noto Rashi Hebrew', FontStyle.italic, FontWeight.bold),
    ('Noto Rashi Hebrew', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Old Permic', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Old Permic', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Old Permic', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Old Permic', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Adlam Unjoined', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Adlam Unjoined', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Adlam Unjoined', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Adlam Unjoined', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Saurashtra', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Saurashtra', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Saurashtra', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Saurashtra', FontStyle.italic, FontWeight.bold),
    ('Fira Code', FontStyle.normal, FontWeight.normal),
    ('Fira Code', FontStyle.italic, FontWeight.normal),
    ('Fira Code', FontStyle.italic, FontWeight.bold),
    ('Fira Code', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Medefaidrin', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Medefaidrin', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Medefaidrin', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Medefaidrin', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Mahajani', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Mahajani', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Mahajani', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Mahajani', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Pau Cin Hau', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Pau Cin Hau', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Pau Cin Hau', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Pau Cin Hau', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Tagbanwa', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Tagbanwa', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Tagbanwa', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Tagbanwa', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Tifinagh Rhissa Ixa', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Tifinagh Rhissa Ixa', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Tifinagh Rhissa Ixa', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Tifinagh Rhissa Ixa', FontStyle.italic, FontWeight.bold),
    ('Liberation Serif', FontStyle.normal, FontWeight.normal),
    ('Liberation Serif', FontStyle.normal, FontWeight.bold),
    ('Liberation Serif', FontStyle.italic, FontWeight.normal),
    ('Liberation Serif', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Adlam', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Adlam', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Adlam', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Adlam', FontStyle.normal, FontWeight.bold),
    ('Noto Serif CJK JP', FontStyle.normal, FontWeight.normal),
    ('Noto Serif CJK JP', FontStyle.italic, FontWeight.normal),
    ('Noto Serif CJK JP', FontStyle.italic, FontWeight.bold),
    ('Noto Serif CJK JP', FontStyle.normal, FontWeight.bold),
    ('Noto Serif CJK HK', FontStyle.normal, FontWeight.normal),
    ('Noto Serif CJK HK', FontStyle.italic, FontWeight.normal),
    ('Noto Serif CJK HK', FontStyle.italic, FontWeight.bold),
    ('Noto Serif CJK HK', FontStyle.normal, FontWeight.bold),
    ('Noto Serif CJK KR', FontStyle.normal, FontWeight.normal),
    ('Noto Serif CJK KR', FontStyle.italic, FontWeight.normal),
    ('Noto Serif CJK KR', FontStyle.italic, FontWeight.bold),
    ('Noto Serif CJK KR', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Lycian', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Lycian', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Lycian', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Lycian', FontStyle.italic, FontWeight.bold),
    ('DejaVu Serif', FontStyle.normal, FontWeight.normal),
    ('DejaVu Serif', FontStyle.normal, FontWeight.bold),
    ('DejaVu Serif', FontStyle.italic, FontWeight.normal),
    ('DejaVu Serif', FontStyle.italic, FontWeight.bold),
    ('Noto Kufi Arabic', FontStyle.normal, FontWeight.normal),
    ('Noto Kufi Arabic', FontStyle.italic, FontWeight.normal),
    ('Noto Kufi Arabic', FontStyle.italic, FontWeight.bold),
    ('Noto Kufi Arabic', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Masaram Gondi', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Masaram Gondi', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Masaram Gondi', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Masaram Gondi', FontStyle.italic, FontWeight.bold),
    ('Ubuntu Mono', FontStyle.normal, FontWeight.normal),
    ('Ubuntu Mono', FontStyle.normal, FontWeight.bold),
    ('Ubuntu Mono', FontStyle.italic, FontWeight.normal),
    ('Ubuntu Mono', FontStyle.italic, FontWeight.bold),
    ('Noto Serif CJK SC', FontStyle.normal, FontWeight.normal),
    ('Noto Serif CJK SC', FontStyle.italic, FontWeight.normal),
    ('Noto Serif CJK SC', FontStyle.italic, FontWeight.bold),
    ('Noto Serif CJK SC', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Palmyrene', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Palmyrene', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Palmyrene', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Palmyrene', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Sora Sompeng', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Sora Sompeng', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Sora Sompeng', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Sora Sompeng', FontStyle.normal, FontWeight.bold),
    ('Noto Serif CJK TC', FontStyle.normal, FontWeight.normal),
    ('Noto Serif CJK TC', FontStyle.italic, FontWeight.normal),
    ('Noto Serif CJK TC', FontStyle.italic, FontWeight.bold),
    ('Noto Serif CJK TC', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Bengali', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Bengali', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Bengali', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Bengali', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Symbols', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Symbols', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Symbols', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Symbols', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Gurmukhi', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Gurmukhi', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Gurmukhi', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Gurmukhi', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Linear B', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Linear B', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Linear B', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Linear B', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Linear A', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Linear A', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Linear A', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Linear A', FontStyle.italic, FontWeight.bold),
    ('Impact', FontStyle.normal, FontWeight.normal),
    ('Impact', FontStyle.italic, FontWeight.normal),
    ('Impact', FontStyle.normal, FontWeight.bold),
    ('Impact', FontStyle.italic, FontWeight.bold),
    ('Noto Serif Hmong Nyiakeng', FontStyle.normal, FontWeight.normal),
    ('Noto Serif Hmong Nyiakeng', FontStyle.italic, FontWeight.normal),
    ('Noto Serif Hmong Nyiakeng', FontStyle.italic, FontWeight.bold),
    ('Noto Serif Hmong Nyiakeng', FontStyle.normal, FontWeight.bold),
    ('Open Sans', FontStyle.normal, FontWeight.normal),
    ('Open Sans', FontStyle.normal, FontWeight.bold),
    ('Open Sans', FontStyle.italic, FontWeight.normal),
    ('Open Sans', FontStyle.italic, FontWeight.bold),
    ('Noto Music', FontStyle.normal, FontWeight.normal),
    ('Noto Music', FontStyle.italic, FontWeight.normal),
    ('Noto Music', FontStyle.normal, FontWeight.bold),
    ('Noto Music', FontStyle.italic, FontWeight.bold),
    ('Liberation Mono', FontStyle.normal, FontWeight.normal),
    ('Liberation Mono', FontStyle.normal, FontWeight.bold),
    ('Liberation Mono', FontStyle.italic, FontWeight.normal),
    ('Liberation Mono', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Grantha', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Grantha', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Grantha', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Grantha', FontStyle.italic, FontWeight.bold),
    ('Arial Black', FontStyle.normal, FontWeight.normal),
    ('Arial Black', FontStyle.italic, FontWeight.normal),
    ('Arial Black', FontStyle.normal, FontWeight.bold),
    ('Arial Black', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Tai Le', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Tai Le', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Tai Le', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Tai Le', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Coptic', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Coptic', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Coptic', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Coptic', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Mono', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Mono', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Mono', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Mono', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Tirhuta', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Tirhuta', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Tirhuta', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Tirhuta', FontStyle.italic, FontWeight.bold),
    ('Trebuchet MS', FontStyle.normal, FontWeight.normal),
    ('Trebuchet MS', FontStyle.normal, FontWeight.bold),
    ('Trebuchet MS', FontStyle.italic, FontWeight.normal),
    ('Trebuchet MS', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Gunjala Gondi', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Gunjala Gondi', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Gunjala Gondi', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Gunjala Gondi', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Hanifi Rohingya', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Hanifi Rohingya', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Hanifi Rohingya', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Hanifi Rohingya', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Ogham', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Ogham', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Ogham', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Ogham', FontStyle.italic, FontWeight.bold),
    ('Andale Mono', FontStyle.normal, FontWeight.normal),
    ('Andale Mono', FontStyle.italic, FontWeight.normal),
    ('Andale Mono', FontStyle.normal, FontWeight.bold),
    ('Andale Mono', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Sharada', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Sharada', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Sharada', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Sharada', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Javanese', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Javanese', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Javanese', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Javanese', FontStyle.normal, FontWeight.bold),
    ('DejaVu Sans', FontStyle.normal, FontWeight.normal),
    ('DejaVu Sans', FontStyle.normal, FontWeight.bold),
    ('DejaVu Sans', FontStyle.normal, FontWeight.normal),
    ('DejaVu Sans', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Elymaic', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Elymaic', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Elymaic', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Elymaic', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Syriac', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Syriac', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Syriac', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Syriac', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Vai', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Vai', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Vai', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Vai', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Oriya', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Oriya', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Oriya', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Oriya', FontStyle.normal, FontWeight.bold),
    ('FreeMono', FontStyle.normal, FontWeight.normal),
    ('FreeMono', FontStyle.normal, FontWeight.bold),
    ('FreeMono', FontStyle.normal, FontWeight.normal),
    ('FreeMono', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Psalter Pahlavi', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Psalter Pahlavi', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Psalter Pahlavi', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Psalter Pahlavi', FontStyle.italic, FontWeight.bold),
    ('Noto Traditional Nushu', FontStyle.normal, FontWeight.normal),
    ('Noto Traditional Nushu', FontStyle.italic, FontWeight.normal),
    ('Noto Traditional Nushu', FontStyle.normal, FontWeight.bold),
    ('Noto Traditional Nushu', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Cypriot', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Cypriot', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Cypriot', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Cypriot', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Old Turkic', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Old Turkic', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Old Turkic', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Old Turkic', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Meetei Mayek', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Meetei Mayek', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Meetei Mayek', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Meetei Mayek', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Meroitic', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Meroitic', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Meroitic', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Meroitic', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Tifinagh SIL', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Tifinagh SIL', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Tifinagh SIL', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Tifinagh SIL', FontStyle.italic, FontWeight.bold),
    ('Liberation Sans', FontStyle.normal, FontWeight.normal),
    ('Liberation Sans', FontStyle.normal, FontWeight.bold),
    ('Liberation Sans', FontStyle.italic, FontWeight.normal),
    ('Liberation Sans', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Yi', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Yi', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Yi', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Yi', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Lisu', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Lisu', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Lisu', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Lisu', FontStyle.normal, FontWeight.bold),
    ('Noto Serif Gujarati', FontStyle.normal, FontWeight.normal),
    ('Noto Serif Gujarati', FontStyle.italic, FontWeight.normal),
    ('Noto Serif Gujarati', FontStyle.italic, FontWeight.bold),
    ('Noto Serif Gujarati', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Samaritan', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Samaritan', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Samaritan', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Samaritan', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Pahawh Hmong', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Pahawh Hmong', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Pahawh Hmong', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Pahawh Hmong', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Tai Tham', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Tai Tham', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Tai Tham', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Tai Tham', FontStyle.normal, FontWeight.bold),
    ('Arial', FontStyle.normal, FontWeight.normal),
    ('Arial', FontStyle.normal, FontWeight.bold),
    ('Arial', FontStyle.italic, FontWeight.normal),
    ('Arial', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Marchen', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Marchen', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Marchen', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Marchen', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Cuneiform', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Cuneiform', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Cuneiform', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Cuneiform', FontStyle.italic, FontWeight.bold),
    ('Courier New', FontStyle.normal, FontWeight.normal),
    ('Courier New', FontStyle.normal, FontWeight.bold),
    ('Courier New', FontStyle.italic, FontWeight.normal),
    ('Courier New', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Kaithi', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Kaithi', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Kaithi', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Kaithi', FontStyle.italic, FontWeight.bold),
    ('Webdings', FontStyle.normal, FontWeight.normal),
    ('Webdings', FontStyle.italic, FontWeight.normal),
    ('Webdings', FontStyle.normal, FontWeight.bold),
    ('Webdings', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Tifinagh Adrar', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Tifinagh Adrar', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Tifinagh Adrar', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Tifinagh Adrar', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Carian', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Carian', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Carian', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Carian', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Nushu', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Nushu', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Nushu', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Nushu', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Anatolian Hieroglyphs', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Anatolian Hieroglyphs', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Anatolian Hieroglyphs', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Anatolian Hieroglyphs', FontStyle.italic, FontWeight.bold),
    ('DejaVu Math TeX Gyre', FontStyle.normal, FontWeight.normal),
    ('DejaVu Math TeX Gyre', FontStyle.italic, FontWeight.normal),
    ('DejaVu Math TeX Gyre', FontStyle.normal, FontWeight.bold),
    ('DejaVu Math TeX Gyre', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Rejang', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Rejang', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Rejang', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Rejang', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Mro', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Mro', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Mro', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Mro', FontStyle.italic, FontWeight.bold),
    ('Noto Sans NKo', FontStyle.normal, FontWeight.normal),
    ('Noto Sans NKo', FontStyle.italic, FontWeight.normal),
    ('Noto Sans NKo', FontStyle.normal, FontWeight.bold),
    ('Noto Sans NKo', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Tifinagh Agraw Imazighen', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Tifinagh Agraw Imazighen', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Tifinagh Agraw Imazighen', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Tifinagh Agraw Imazighen', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Tamil Supplement', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Tamil Supplement', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Tamil Supplement', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Tamil Supplement', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Imperial Aramaic', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Imperial Aramaic', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Imperial Aramaic', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Imperial Aramaic', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Tai Viet', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Tai Viet', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Tai Viet', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Tai Viet', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Caucasian Albanian', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Caucasian Albanian', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Caucasian Albanian', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Caucasian Albanian', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Old South Arabian', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Old South Arabian', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Old South Arabian', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Old South Arabian', FontStyle.italic, FontWeight.bold),
    ('FreeSans', FontStyle.normal, FontWeight.normal),
    ('FreeSans', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Mongolian', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Mongolian', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Mongolian', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Mongolian', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Tifinagh Tawellemmet', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Tifinagh Tawellemmet', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Tifinagh Tawellemmet', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Tifinagh Tawellemmet', FontStyle.italic, FontWeight.bold),
    ('Comic Sans MS', FontStyle.normal, FontWeight.normal),
    ('Comic Sans MS', FontStyle.italic, FontWeight.normal),
    ('Comic Sans MS', FontStyle.italic, FontWeight.bold),
    ('Comic Sans MS', FontStyle.normal, FontWeight.bold),
    ('Verdana', FontStyle.normal, FontWeight.normal),
    ('Verdana', FontStyle.normal, FontWeight.bold),
    ('Verdana', FontStyle.italic, FontWeight.normal),
    ('Verdana', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Limbu', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Limbu', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Limbu', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Limbu', FontStyle.italic, FontWeight.bold),
    ('FreeSerif', FontStyle.normal, FontWeight.normal),
    ('FreeSerif', FontStyle.normal, FontWeight.bold),
    ('FreeSerif', FontStyle.italic, FontWeight.normal),
    ('FreeSerif', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Kharoshthi', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Kharoshthi', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Kharoshthi', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Kharoshthi', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Tifinagh Air', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Tifinagh Air', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Tifinagh Air', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Tifinagh Air', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Tifinagh Ghat', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Tifinagh Ghat', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Tifinagh Ghat', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Tifinagh Ghat', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Glagolitic', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Glagolitic', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Glagolitic', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Glagolitic', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Old North Arabian', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Old North Arabian', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Old North Arabian', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Old North Arabian', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Tifinagh APT', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Tifinagh APT', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Tifinagh APT', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Tifinagh APT', FontStyle.italic, FontWeight.bold),
    ('Linux Biolinum Keyboard O', FontStyle.italic, FontWeight.bold),
    ('Linux Biolinum Keyboard O', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Syloti Nagri', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Syloti Nagri', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Syloti Nagri', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Syloti Nagri', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Bamum', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Bamum', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Bamum', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Bamum', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Multani', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Multani', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Multani', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Multani', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Mayan Numerals', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Mayan Numerals', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Mayan Numerals', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Mayan Numerals', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Deseret', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Deseret', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Deseret', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Deseret', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Lydian', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Lydian', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Lydian', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Lydian', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Ol Chiki', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Ol Chiki', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Ol Chiki', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Ol Chiki', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Takri', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Takri', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Takri', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Takri', FontStyle.italic, FontWeight.bold),
    ('Noto Serif Tangut', FontStyle.normal, FontWeight.normal),
    ('Noto Serif Tangut', FontStyle.italic, FontWeight.normal),
    ('Noto Serif Tangut', FontStyle.normal, FontWeight.bold),
    ('Noto Serif Tangut', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Buginese', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Buginese', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Buginese', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Buginese', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Sogdian', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Sogdian', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Sogdian', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Sogdian', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Siddham', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Siddham', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Siddham', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Siddham', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Duployan', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Duployan', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Duployan', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Duployan', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Khudawadi', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Khudawadi', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Khudawadi', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Khudawadi', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Gothic', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Gothic', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Gothic', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Gothic', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Mandaic', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Mandaic', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Mandaic', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Mandaic', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Old Italic', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Old Italic', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Old Italic', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Old Italic', FontStyle.italic, FontWeight.bold),
    ('Open Sans Condensed', FontStyle.italic, FontWeight.bold),
    ('Open Sans Condensed', FontStyle.normal, FontWeight.bold),
    ('Linux Biolinum O', FontStyle.normal, FontWeight.normal),
    ('Linux Biolinum O', FontStyle.italic, FontWeight.bold),
    ('Linux Biolinum O', FontStyle.normal, FontWeight.bold),
    ('Linux Biolinum O', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Old Sogdian', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Old Sogdian', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Old Sogdian', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Old Sogdian', FontStyle.italic, FontWeight.bold),
    ('Noto Serif Dogra', FontStyle.normal, FontWeight.normal),
    ('Noto Serif Dogra', FontStyle.italic, FontWeight.normal),
    ('Noto Serif Dogra', FontStyle.normal, FontWeight.bold),
    ('Noto Serif Dogra', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Mende Kikakui', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Mende Kikakui', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Mende Kikakui', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Mende Kikakui', FontStyle.italic, FontWeight.bold),
    ('Noto Nastaliq Urdu', FontStyle.normal, FontWeight.normal),
    ('Noto Nastaliq Urdu', FontStyle.italic, FontWeight.normal),
    ('Noto Nastaliq Urdu', FontStyle.normal, FontWeight.bold),
    ('Noto Nastaliq Urdu', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Hatran', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Hatran', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Hatran', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Hatran', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Newa', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Newa', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Newa', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Newa', FontStyle.italic, FontWeight.bold),
    ('Linux Libertine Initials O', FontStyle.normal, FontWeight.normal),
    ('Linux Libertine Initials O', FontStyle.italic, FontWeight.normal),
    ('Linux Libertine Initials O', FontStyle.normal, FontWeight.bold),
    ('Linux Libertine Initials O', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Khojki', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Khojki', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Khojki', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Khojki', FontStyle.italic, FontWeight.bold),
    ('Linux Libertine Mono O', FontStyle.normal, FontWeight.normal),
    ('Linux Libertine Mono O', FontStyle.italic, FontWeight.normal),
    ('Linux Libertine Mono O', FontStyle.normal, FontWeight.bold),
    ('Linux Libertine Mono O', FontStyle.italic, FontWeight.bold),
    ('Symbola', FontStyle.normal, FontWeight.normal),
    ('Symbola', FontStyle.italic, FontWeight.normal),
    ('Symbola', FontStyle.normal, FontWeight.bold),
    ('Symbola', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Math', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Math', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Math', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Math', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Inscriptional Pahlavi', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Inscriptional Pahlavi', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Inscriptional Pahlavi', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Inscriptional Pahlavi', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Tifinagh', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Tifinagh', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Tifinagh', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Tifinagh', FontStyle.italic, FontWeight.bold),
    ('Noto Serif Balinese', FontStyle.normal, FontWeight.normal),
    ('Noto Serif Balinese', FontStyle.italic, FontWeight.normal),
    ('Noto Serif Balinese', FontStyle.normal, FontWeight.bold),
    ('Noto Serif Balinese', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Soyombo', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Soyombo', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Soyombo', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Soyombo', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Hanunoo', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Hanunoo', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Hanunoo', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Hanunoo', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Bhaiksuki', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Bhaiksuki', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Bhaiksuki', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Bhaiksuki', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Wancho', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Wancho', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Wancho', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Wancho', FontStyle.italic, FontWeight.bold),
    ('Noto Sans PhagsPa', FontStyle.normal, FontWeight.normal),
    ('Noto Sans PhagsPa', FontStyle.italic, FontWeight.normal),
    ('Noto Sans PhagsPa', FontStyle.normal, FontWeight.bold),
    ('Noto Sans PhagsPa', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Inscriptional Parthian', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Inscriptional Parthian', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Inscriptional Parthian', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Inscriptional Parthian', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Tifinagh Hawad', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Tifinagh Hawad', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Tifinagh Hawad', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Tifinagh Hawad', FontStyle.italic, FontWeight.bold),
    ('Noto Mono', FontStyle.normal, FontWeight.normal),
    ('Noto Mono', FontStyle.italic, FontWeight.normal),
    ('Noto Mono', FontStyle.normal, FontWeight.bold),
    ('Noto Mono', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Old Persian', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Old Persian', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Old Persian', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Old Persian', FontStyle.italic, FontWeight.bold),
    ('Noto Serif Grantha', FontStyle.normal, FontWeight.normal),
    ('Noto Serif Grantha', FontStyle.italic, FontWeight.normal),
    ('Noto Serif Grantha', FontStyle.normal, FontWeight.bold),
    ('Noto Serif Grantha', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Phoenician', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Phoenician', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Phoenician', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Phoenician', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Indic Siyaq Numbers', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Indic Siyaq Numbers', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Indic Siyaq Numbers', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Indic Siyaq Numbers', FontStyle.italic, FontWeight.bold),
    ('Noto Color Emoji', FontStyle.normal, FontWeight.normal),
    ('Noto Color Emoji', FontStyle.italic, FontWeight.normal),
    ('Noto Color Emoji', FontStyle.normal, FontWeight.bold),
    ('Noto Color Emoji', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Tagalog', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Tagalog', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Tagalog', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Tagalog', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Shavian', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Shavian', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Shavian', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Shavian', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Batak', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Batak', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Batak', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Batak', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Old Hungarian', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Old Hungarian', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Old Hungarian', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Old Hungarian', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Miao', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Miao', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Miao', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Miao', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Osage', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Osage', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Osage', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Osage', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Egyptian Hieroglyphs', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Egyptian Hieroglyphs', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Egyptian Hieroglyphs', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Egyptian Hieroglyphs', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Modi', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Modi', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Modi', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Modi', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Avestan', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Avestan', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Avestan', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Avestan', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Bassa Vah', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Bassa Vah', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Bassa Vah', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Bassa Vah', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Lepcha', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Lepcha', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Lepcha', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Lepcha', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Buhid', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Buhid', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Buhid', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Buhid', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Tifinagh Azawagh', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Tifinagh Azawagh', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Tifinagh Azawagh', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Tifinagh Azawagh', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Symbols2', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Symbols2', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Symbols2', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Symbols2', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Zanabazar Square', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Zanabazar Square', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Zanabazar Square', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Zanabazar Square', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Chakma', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Chakma', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Chakma', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Chakma', FontStyle.italic, FontWeight.bold),
    ('Noto Sans SignWriting', FontStyle.normal, FontWeight.normal),
    ('Noto Sans SignWriting', FontStyle.italic, FontWeight.normal),
    ('Noto Sans SignWriting', FontStyle.normal, FontWeight.bold),
    ('Noto Sans SignWriting', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Elbasan', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Elbasan', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Elbasan', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Elbasan', FontStyle.italic, FontWeight.bold),
    ('Noto Sans Runic', FontStyle.normal, FontWeight.normal),
    ('Noto Sans Runic', FontStyle.italic, FontWeight.normal),
    ('Noto Sans Runic', FontStyle.normal, FontWeight.bold),
    ('Noto Sans Runic', FontStyle.italic, FontWeight.bold),
    ('Sans', FontStyle.normal, FontWeight.normal),
    ('Sans', FontStyle.normal, FontWeight.bold),
    ('Sans', FontStyle.italic, FontWeight.normal),
    ('Sans', FontStyle.italic, FontWeight.bold),
    ('Serif', FontStyle.normal, FontWeight.normal),
    ('Serif', FontStyle.normal, FontWeight.bold),
    ('Serif', FontStyle.italic, FontWeight.normal),
    ('Serif', FontStyle.italic, FontWeight.bold),
    ('Monospace', FontStyle.normal, FontWeight.normal),
    ('Monospace', FontStyle.normal, FontWeight.bold),
    ('Monospace', FontStyle.italic, FontWeight.normal),
    ('Monospace', FontStyle.italic, FontWeight.bold),
    ('System-ui', FontStyle.normal, FontWeight.normal),
    ('System-ui', FontStyle.normal, FontWeight.bold),
    ('System-ui', FontStyle.italic, FontWeight.normal),
    ('System-ui', FontStyle.italic, FontWeight.bold),
    ('Inter', FontStyle.normal, FontWeight.normal),
    ('Inter', FontStyle.normal, FontWeight.bold),
    ('Inter', FontStyle.italic, FontWeight.normal),
    ('Inter', FontStyle.italic, FontWeight.bold),
    ('Inter', FontStyle.normal, FontWeight.w300),
    ('Inter', FontStyle.italic, FontWeight.w300),
    ('Inter', FontStyle.normal, FontWeight.w500),
    ('Inter', FontStyle.italic, FontWeight.w500),
    ('Inter', FontStyle.normal, FontWeight.w600),
    ('Inter', FontStyle.italic, FontWeight.w600),
    ('System', FontStyle.normal, FontWeight.normal),
    ('System', FontStyle.normal, FontWeight.bold),
    ('System', FontStyle.italic, FontWeight.normal),
    ('System', FontStyle.italic, FontWeight.bold),
    ('System', FontStyle.normal, FontWeight.w300),
    ('System', FontStyle.italic, FontWeight.w300),
    ('System', FontStyle.normal, FontWeight.w500),
    ('System', FontStyle.italic, FontWeight.w500),
    ('System', FontStyle.normal, FontWeight.w600),
    ('System', FontStyle.italic, FontWeight.w600),
  ];
}
