import 'dart:ui';

const AllFonts = [
  ('Academy Engraved LET', FontStyle.normal, FontWeight.normal),
  ('Al Bayan', FontStyle.normal, FontWeight.normal),
  ('Al Bayan', FontStyle.normal, FontWeight.bold),
  ('Al Nile', FontStyle.normal, FontWeight.normal),
  ('Al Nile', FontStyle.normal, FontWeight.bold),
  ('Al Tarikh', FontStyle.normal, FontWeight.normal),
  ('American Typewriter', FontStyle.normal, FontWeight.normal),
  ('American Typewriter', FontStyle.normal, FontWeight.bold),
  ('Andale Mono', FontStyle.normal, FontWeight.normal),
  ('Apple Braille', FontStyle.normal, FontWeight.normal),
  ('Apple Chancery', FontStyle.normal, FontWeight.normal),
  ('Apple Color Emoji', FontStyle.normal, FontWeight.normal),
  ('Apple SD Gothic Neo', FontStyle.normal, FontWeight.normal),
  ('Apple SD Gothic Neo', FontStyle.normal, FontWeight.bold),
  ('Apple Symbols', FontStyle.normal, FontWeight.normal),
  ('AppleGothic', FontStyle.normal, FontWeight.normal),
  ('AppleMyungjo', FontStyle.normal, FontWeight.normal),
  ('Arial', FontStyle.normal, FontWeight.normal),
  ('Arial', FontStyle.italic, FontWeight.normal),
  ('Arial', FontStyle.normal, FontWeight.bold),
  ('Arial', FontStyle.italic, FontWeight.bold),
  ('Arial Black', FontStyle.normal, FontWeight.normal),
  ('Arial Hebrew', FontStyle.normal, FontWeight.normal),
  ('Arial Hebrew', FontStyle.normal, FontWeight.bold),
  ('Arial Hebrew Scholar', FontStyle.normal, FontWeight.normal),
  ('Arial Hebrew Scholar', FontStyle.normal, FontWeight.bold),
  ('Arial Narrow', FontStyle.normal, FontWeight.normal),
  ('Arial Narrow', FontStyle.italic, FontWeight.normal),
  ('Arial Narrow', FontStyle.normal, FontWeight.bold),
  ('Arial Narrow', FontStyle.italic, FontWeight.bold),
  ('Arial Rounded MT Bold', FontStyle.normal, FontWeight.normal),
  ('Arial Unicode MS', FontStyle.normal, FontWeight.normal),
  ('Avenir', FontStyle.normal, FontWeight.normal),
  ('Avenir', FontStyle.italic, FontWeight.normal),
  ('Avenir Next', FontStyle.normal, FontWeight.normal),
  ('Avenir Next', FontStyle.italic, FontWeight.normal),
  ('Avenir Next', FontStyle.normal, FontWeight.bold),
  ('Avenir Next', FontStyle.italic, FontWeight.bold),
  ('Avenir Next Condensed', FontStyle.normal, FontWeight.normal),
  ('Avenir Next Condensed', FontStyle.italic, FontWeight.normal),
  ('Avenir Next Condensed', FontStyle.normal, FontWeight.bold),
  ('Avenir Next Condensed', FontStyle.italic, FontWeight.bold),
  ('Ayuthaya', FontStyle.normal, FontWeight.normal),
  ('Baghdad', FontStyle.normal, FontWeight.normal),
  ('Bangla MN', FontStyle.normal, FontWeight.normal),
  ('Bangla MN', FontStyle.normal, FontWeight.bold),
  ('Bangla Sangam MN', FontStyle.normal, FontWeight.normal),
  ('Bangla Sangam MN', FontStyle.normal, FontWeight.bold),
  ('Baskerville', FontStyle.normal, FontWeight.normal),
  ('Baskerville', FontStyle.italic, FontWeight.normal),
  ('Baskerville', FontStyle.normal, FontWeight.bold),
  ('Baskerville', FontStyle.italic, FontWeight.bold),
  ('Beirut', FontStyle.normal, FontWeight.bold),
  ('Big Caslon', FontStyle.normal, FontWeight.normal),
  ('Bodoni 72', FontStyle.normal, FontWeight.normal),
  ('Bodoni 72', FontStyle.italic, FontWeight.normal),
  ('Bodoni 72', FontStyle.normal, FontWeight.bold),
  ('Bodoni 72 Oldstyle', FontStyle.normal, FontWeight.normal),
  ('Bodoni 72 Oldstyle', FontStyle.italic, FontWeight.normal),
  ('Bodoni 72 Oldstyle', FontStyle.normal, FontWeight.bold),
  ('Bodoni 72 Smallcaps', FontStyle.normal, FontWeight.normal),
  ('Bodoni Ornaments', FontStyle.normal, FontWeight.normal),
  ('Bradley Hand', FontStyle.normal, FontWeight.bold),
  ('Brush Script MT', FontStyle.normal, FontWeight.normal),
  ('Chalkboard', FontStyle.normal, FontWeight.normal),
  ('Chalkboard', FontStyle.normal, FontWeight.bold),
  ('Chalkboard SE', FontStyle.normal, FontWeight.normal),
  ('Chalkboard SE', FontStyle.normal, FontWeight.bold),
  ('Chalkduster', FontStyle.normal, FontWeight.normal),
  ('Charter', FontStyle.normal, FontWeight.normal),
  ('Charter', FontStyle.italic, FontWeight.normal),
  ('Charter', FontStyle.normal, FontWeight.bold),
  ('Charter', FontStyle.italic, FontWeight.bold),
  ('Cochin', FontStyle.normal, FontWeight.normal),
  ('Cochin', FontStyle.italic, FontWeight.normal),
  ('Cochin', FontStyle.normal, FontWeight.bold),
  ('Cochin', FontStyle.italic, FontWeight.bold),
  ('Comic Sans MS', FontStyle.normal, FontWeight.normal),
  ('Comic Sans MS', FontStyle.normal, FontWeight.bold),
  ('Copperplate', FontStyle.normal, FontWeight.normal),
  ('Copperplate', FontStyle.normal, FontWeight.bold),
  ('Corsiva Hebrew', FontStyle.normal, FontWeight.normal),
  ('Corsiva Hebrew', FontStyle.normal, FontWeight.bold),
  ('Courier New', FontStyle.normal, FontWeight.normal),
  ('Courier New', FontStyle.italic, FontWeight.normal),
  ('Courier New', FontStyle.normal, FontWeight.bold),
  ('Courier New', FontStyle.italic, FontWeight.bold),
  ('Damascus', FontStyle.normal, FontWeight.normal),
  ('Damascus', FontStyle.normal, FontWeight.bold),
  ('DecoType Naskh', FontStyle.normal, FontWeight.normal),
  ('Devanagari MT', FontStyle.normal, FontWeight.normal),
  ('Devanagari MT', FontStyle.normal, FontWeight.bold),
  ('Devanagari Sangam MN', FontStyle.normal, FontWeight.normal),
  ('Devanagari Sangam MN', FontStyle.normal, FontWeight.bold),
  ('Didot', FontStyle.normal, FontWeight.normal),
  ('Didot', FontStyle.italic, FontWeight.normal),
  ('Didot', FontStyle.normal, FontWeight.bold),
  ('DIN Alternate', FontStyle.normal, FontWeight.bold),
  ('DIN Condensed', FontStyle.normal, FontWeight.bold),
  ('Diwan Kufi', FontStyle.normal, FontWeight.normal),
  ('Diwan Thuluth', FontStyle.normal, FontWeight.normal),
  ('Euphemia UCAS', FontStyle.normal, FontWeight.normal),
  ('Euphemia UCAS', FontStyle.italic, FontWeight.normal),
  ('Euphemia UCAS', FontStyle.normal, FontWeight.bold),
  ('Farah', FontStyle.normal, FontWeight.normal),
  ('Farisi', FontStyle.normal, FontWeight.normal),
  ('Futura', FontStyle.normal, FontWeight.normal),
  ('Futura', FontStyle.italic, FontWeight.normal),
  ('Futura', FontStyle.normal, FontWeight.bold),
  ('Galvji', FontStyle.normal, FontWeight.normal),
  ('Galvji', FontStyle.italic, FontWeight.normal),
  ('Galvji', FontStyle.normal, FontWeight.bold),
  ('Galvji', FontStyle.italic, FontWeight.bold),
  ('GB18030 Bitmap', FontStyle.normal, FontWeight.normal),
  ('Geeza Pro', FontStyle.normal, FontWeight.normal),
  ('Geeza Pro', FontStyle.normal, FontWeight.bold),
  ('Geneva', FontStyle.normal, FontWeight.normal),
  ('Georgia', FontStyle.normal, FontWeight.normal),
  ('Georgia', FontStyle.italic, FontWeight.normal),
  ('Georgia', FontStyle.normal, FontWeight.bold),
  ('Georgia', FontStyle.italic, FontWeight.bold),
  ('Gill Sans', FontStyle.normal, FontWeight.normal),
  ('Gill Sans', FontStyle.italic, FontWeight.normal),
  ('Gill Sans', FontStyle.normal, FontWeight.bold),
  ('Gill Sans', FontStyle.italic, FontWeight.bold),
  ('Grantha Sangam MN', FontStyle.normal, FontWeight.normal),
  ('Grantha Sangam MN', FontStyle.normal, FontWeight.bold),
  ('Gujarati MT', FontStyle.normal, FontWeight.normal),
  ('Gujarati MT', FontStyle.normal, FontWeight.bold),
  ('Gujarati Sangam MN', FontStyle.normal, FontWeight.normal),
  ('Gujarati Sangam MN', FontStyle.normal, FontWeight.bold),
  ('Gurmukhi MN', FontStyle.normal, FontWeight.normal),
  ('Gurmukhi MN', FontStyle.normal, FontWeight.bold),
  ('Gurmukhi MT', FontStyle.normal, FontWeight.normal),
  ('Gurmukhi Sangam MN', FontStyle.normal, FontWeight.normal),
  ('Gurmukhi Sangam MN', FontStyle.normal, FontWeight.bold),
  ('Heiti SC', FontStyle.normal, FontWeight.normal),
  ('Heiti SC', FontStyle.normal, FontWeight.bold),
  ('Heiti TC', FontStyle.normal, FontWeight.normal),
  ('Heiti TC', FontStyle.normal, FontWeight.bold),
  ('Helvetica', FontStyle.normal, FontWeight.normal),
  ('Helvetica', FontStyle.italic, FontWeight.normal),
  ('Helvetica', FontStyle.normal, FontWeight.bold),
  ('Helvetica', FontStyle.italic, FontWeight.bold),
  ('Helvetica Neue', FontStyle.normal, FontWeight.normal),
  ('Helvetica Neue', FontStyle.italic, FontWeight.normal),
  ('Helvetica Neue', FontStyle.normal, FontWeight.bold),
  ('Helvetica Neue', FontStyle.italic, FontWeight.bold),
  ('Herculanum', FontStyle.normal, FontWeight.normal),
  ('Hiragino Maru Gothic ProN', FontStyle.normal, FontWeight.normal),
  ('Hiragino Mincho ProN', FontStyle.normal, FontWeight.normal),
  ('Hiragino Sans', FontStyle.normal, FontWeight.normal),
  ('Hiragino Sans', FontStyle.normal, FontWeight.bold),
  ('Hiragino Sans GB', FontStyle.normal, FontWeight.normal),
  ('Hoefler Text', FontStyle.normal, FontWeight.normal),
  ('Hoefler Text', FontStyle.italic, FontWeight.normal),
  ('Hoefler Text', FontStyle.normal, FontWeight.bold),
  ('Hoefler Text', FontStyle.italic, FontWeight.bold),
  ('Impact', FontStyle.normal, FontWeight.normal),
  ('InaiMathi', FontStyle.normal, FontWeight.normal),
  ('InaiMathi', FontStyle.normal, FontWeight.bold),
  ('ITF Devanagari', FontStyle.normal, FontWeight.normal),
  ('ITF Devanagari', FontStyle.normal, FontWeight.bold),
  ('ITF Devanagari Marathi', FontStyle.normal, FontWeight.normal),
  ('ITF Devanagari Marathi', FontStyle.normal, FontWeight.bold),
  ('Kailasa', FontStyle.normal, FontWeight.normal),
  ('Kailasa', FontStyle.normal, FontWeight.bold),
  ('Kannada MN', FontStyle.normal, FontWeight.normal),
  ('Kannada MN', FontStyle.normal, FontWeight.bold),
  ('Kannada Sangam MN', FontStyle.normal, FontWeight.normal),
  ('Kannada Sangam MN', FontStyle.normal, FontWeight.bold),
  ('Kefa', FontStyle.normal, FontWeight.normal),
  ('Kefa', FontStyle.normal, FontWeight.bold),
  ('Khmer MN', FontStyle.normal, FontWeight.normal),
  ('Khmer MN', FontStyle.normal, FontWeight.bold),
  ('Khmer Sangam MN', FontStyle.normal, FontWeight.normal),
  ('Kohinoor Bangla', FontStyle.normal, FontWeight.normal),
  ('Kohinoor Bangla', FontStyle.normal, FontWeight.bold),
  ('Kohinoor Devanagari', FontStyle.normal, FontWeight.normal),
  ('Kohinoor Devanagari', FontStyle.normal, FontWeight.bold),
  ('Kohinoor Gujarati', FontStyle.normal, FontWeight.normal),
  ('Kohinoor Gujarati', FontStyle.normal, FontWeight.bold),
  ('Kohinoor Telugu', FontStyle.normal, FontWeight.normal),
  ('Kohinoor Telugu', FontStyle.normal, FontWeight.bold),
  ('Kokonor', FontStyle.normal, FontWeight.normal),
  ('Krungthep', FontStyle.normal, FontWeight.bold),
  ('KufiStandardGK', FontStyle.normal, FontWeight.normal),
  ('Lao MN', FontStyle.normal, FontWeight.normal),
  ('Lao MN', FontStyle.normal, FontWeight.bold),
  ('Lao Sangam MN', FontStyle.normal, FontWeight.normal),
  ('Lucida Grande', FontStyle.normal, FontWeight.normal),
  ('Lucida Grande', FontStyle.normal, FontWeight.bold),
  ('Luminari', FontStyle.normal, FontWeight.normal),
  ('Malayalam MN', FontStyle.normal, FontWeight.normal),
  ('Malayalam MN', FontStyle.normal, FontWeight.bold),
  ('Malayalam Sangam MN', FontStyle.normal, FontWeight.normal),
  ('Malayalam Sangam MN', FontStyle.normal, FontWeight.bold),
  ('Marker Felt', FontStyle.normal, FontWeight.normal),
  ('Marker Felt', FontStyle.normal, FontWeight.bold),
  ('Menlo', FontStyle.normal, FontWeight.normal),
  ('Menlo', FontStyle.italic, FontWeight.normal),
  ('Menlo', FontStyle.normal, FontWeight.bold),
  ('Menlo', FontStyle.italic, FontWeight.bold),
  ('MesloLGS NF', FontStyle.normal, FontWeight.normal),
  ('MesloLGS NF', FontStyle.italic, FontWeight.normal),
  ('MesloLGS NF', FontStyle.normal, FontWeight.bold),
  ('MesloLGS NF', FontStyle.italic, FontWeight.bold),
  ('Microsoft Sans Serif', FontStyle.normal, FontWeight.normal),
  ('Mishafi', FontStyle.normal, FontWeight.normal),
  ('Mishafi Gold', FontStyle.normal, FontWeight.normal),
  ('Monaco', FontStyle.normal, FontWeight.normal),
  ('Mshtakan', FontStyle.normal, FontWeight.normal),
  ('Mshtakan', FontStyle.italic, FontWeight.normal),
  ('Mshtakan', FontStyle.normal, FontWeight.bold),
  ('Mshtakan', FontStyle.italic, FontWeight.bold),
  ('Mukta Mahee', FontStyle.normal, FontWeight.normal),
  ('Mukta Mahee', FontStyle.normal, FontWeight.bold),
  ('Muna', FontStyle.normal, FontWeight.normal),
  ('Muna', FontStyle.normal, FontWeight.bold),
  ('Myanmar MN', FontStyle.normal, FontWeight.normal),
  ('Myanmar MN', FontStyle.normal, FontWeight.bold),
  ('Myanmar Sangam MN', FontStyle.normal, FontWeight.normal),
  ('Myanmar Sangam MN', FontStyle.normal, FontWeight.bold),
  ('Nadeem', FontStyle.normal, FontWeight.normal),
  ('New Peninim MT', FontStyle.normal, FontWeight.normal),
  ('New Peninim MT', FontStyle.italic, FontWeight.normal),
  ('New Peninim MT', FontStyle.normal, FontWeight.bold),
  ('New Peninim MT', FontStyle.italic, FontWeight.bold),
  ('Noteworthy', FontStyle.normal, FontWeight.normal),
  ('Noteworthy', FontStyle.normal, FontWeight.bold),
  ('Noto Nastaliq Urdu', FontStyle.normal, FontWeight.normal),
  ('Noto Nastaliq Urdu', FontStyle.normal, FontWeight.bold),
  ('Noto Sans Batak', FontStyle.normal, FontWeight.normal),
  ('Noto Sans Kannada', FontStyle.normal, FontWeight.normal),
  ('Noto Sans Kannada', FontStyle.normal, FontWeight.bold),
  ('Noto Sans Myanmar', FontStyle.normal, FontWeight.normal),
  ('Noto Sans Myanmar', FontStyle.normal, FontWeight.bold),
  ('Noto Sans NKo', FontStyle.normal, FontWeight.normal),
  ('Noto Sans Oriya', FontStyle.normal, FontWeight.normal),
  ('Noto Sans Oriya', FontStyle.normal, FontWeight.bold),
  ('Noto Sans Syriac', FontStyle.normal, FontWeight.normal),
  ('Noto Sans Syriac', FontStyle.normal, FontWeight.bold),
  ('Noto Sans Tagalog', FontStyle.normal, FontWeight.normal),
  ('Noto Serif Myanmar', FontStyle.normal, FontWeight.normal),
  ('Noto Serif Myanmar', FontStyle.normal, FontWeight.bold),
  ('Optima', FontStyle.normal, FontWeight.normal),
  ('Optima', FontStyle.italic, FontWeight.normal),
  ('Optima', FontStyle.normal, FontWeight.bold),
  ('Optima', FontStyle.italic, FontWeight.bold),
  ('Oriya MN', FontStyle.normal, FontWeight.normal),
  ('Oriya MN', FontStyle.normal, FontWeight.bold),
  ('Oriya Sangam MN', FontStyle.normal, FontWeight.normal),
  ('Oriya Sangam MN', FontStyle.normal, FontWeight.bold),
  ('Palatino', FontStyle.normal, FontWeight.normal),
  ('Palatino', FontStyle.italic, FontWeight.normal),
  ('Palatino', FontStyle.normal, FontWeight.bold),
  ('Palatino', FontStyle.italic, FontWeight.bold),
  ('Papyrus', FontStyle.normal, FontWeight.normal),
  ('Party LET', FontStyle.normal, FontWeight.normal),
  ('Phosphate', FontStyle.normal, FontWeight.normal),
  ('PingFang HK', FontStyle.normal, FontWeight.normal),
  ('PingFang MO', FontStyle.normal, FontWeight.normal),
  ('PingFang SC', FontStyle.normal, FontWeight.normal),
  ('PingFang TC', FontStyle.normal, FontWeight.normal),
  ('Plantagenet Cherokee', FontStyle.normal, FontWeight.normal),
  ('PT Mono', FontStyle.normal, FontWeight.normal),
  ('PT Mono', FontStyle.normal, FontWeight.bold),
  ('PT Sans', FontStyle.normal, FontWeight.normal),
  ('PT Sans', FontStyle.italic, FontWeight.normal),
  ('PT Sans', FontStyle.normal, FontWeight.bold),
  ('PT Sans', FontStyle.italic, FontWeight.bold),
  ('PT Sans Caption', FontStyle.normal, FontWeight.normal),
  ('PT Sans Caption', FontStyle.normal, FontWeight.bold),
  ('PT Sans Narrow', FontStyle.normal, FontWeight.normal),
  ('PT Sans Narrow', FontStyle.normal, FontWeight.bold),
  ('PT Serif', FontStyle.normal, FontWeight.normal),
  ('PT Serif', FontStyle.italic, FontWeight.normal),
  ('PT Serif', FontStyle.normal, FontWeight.bold),
  ('PT Serif', FontStyle.italic, FontWeight.bold),
  ('PT Serif Caption', FontStyle.normal, FontWeight.normal),
  ('PT Serif Caption', FontStyle.italic, FontWeight.normal),
  ('Raanana', FontStyle.normal, FontWeight.normal),
  ('Raanana', FontStyle.normal, FontWeight.bold),
  ('Rockwell', FontStyle.normal, FontWeight.normal),
  ('Rockwell', FontStyle.italic, FontWeight.normal),
  ('Rockwell', FontStyle.normal, FontWeight.bold),
  ('Rockwell', FontStyle.italic, FontWeight.bold),
  ('Sana', FontStyle.normal, FontWeight.normal),
  ('Sathu', FontStyle.normal, FontWeight.normal),
  ('Savoye LET', FontStyle.normal, FontWeight.normal),
  ('Shree Devanagari 714', FontStyle.normal, FontWeight.normal),
  ('Shree Devanagari 714', FontStyle.italic, FontWeight.normal),
  ('Shree Devanagari 714', FontStyle.normal, FontWeight.bold),
  ('Shree Devanagari 714', FontStyle.italic, FontWeight.bold),
  ('SignPainter', FontStyle.normal, FontWeight.normal),
  ('Silom', FontStyle.normal, FontWeight.bold),
  ('Sinhala MN', FontStyle.normal, FontWeight.normal),
  ('Sinhala MN', FontStyle.normal, FontWeight.bold),
  ('Sinhala Sangam MN', FontStyle.normal, FontWeight.normal),
  ('Sinhala Sangam MN', FontStyle.normal, FontWeight.bold),
  ('Skia', FontStyle.normal, FontWeight.normal),
  ('Skia', FontStyle.normal, FontWeight.bold),
  ('Snell Roundhand', FontStyle.normal, FontWeight.normal),
  ('Snell Roundhand', FontStyle.normal, FontWeight.bold),
  ('Songti SC', FontStyle.normal, FontWeight.normal),
  ('Songti SC', FontStyle.normal, FontWeight.bold),
  ('Songti TC', FontStyle.normal, FontWeight.normal),
  ('Songti TC', FontStyle.normal, FontWeight.bold),
  ('STIX Two Math', FontStyle.normal, FontWeight.normal),
  ('STIX Two Text', FontStyle.normal, FontWeight.normal),
  ('STIX Two Text', FontStyle.italic, FontWeight.normal),
  ('STIX Two Text', FontStyle.normal, FontWeight.bold),
  ('STIX Two Text', FontStyle.italic, FontWeight.bold),
  ('STSong', FontStyle.normal, FontWeight.normal),
  ('Sukhumvit Set', FontStyle.normal, FontWeight.normal),
  ('Sukhumvit Set', FontStyle.normal, FontWeight.bold),
  ('Symbol', FontStyle.normal, FontWeight.normal),
  ('Tahoma', FontStyle.normal, FontWeight.normal),
  ('Tahoma', FontStyle.normal, FontWeight.bold),
  ('Tamil MN', FontStyle.normal, FontWeight.normal),
  ('Tamil MN', FontStyle.normal, FontWeight.bold),
  ('Tamil Sangam MN', FontStyle.normal, FontWeight.normal),
  ('Tamil Sangam MN', FontStyle.normal, FontWeight.bold),
  ('Telugu MN', FontStyle.normal, FontWeight.normal),
  ('Telugu MN', FontStyle.normal, FontWeight.bold),
  ('Telugu Sangam MN', FontStyle.normal, FontWeight.normal),
  ('Telugu Sangam MN', FontStyle.normal, FontWeight.bold),
  ('Thonburi', FontStyle.normal, FontWeight.normal),
  ('Thonburi', FontStyle.normal, FontWeight.bold),
  ('Times New Roman', FontStyle.normal, FontWeight.normal),
  ('Times New Roman', FontStyle.italic, FontWeight.normal),
  ('Times New Roman', FontStyle.normal, FontWeight.bold),
  ('Times New Roman', FontStyle.italic, FontWeight.bold),
  ('Trattatello', FontStyle.normal, FontWeight.normal),
  ('Trebuchet MS', FontStyle.normal, FontWeight.normal),
  ('Trebuchet MS', FontStyle.italic, FontWeight.normal),
  ('Trebuchet MS', FontStyle.normal, FontWeight.bold),
  ('Trebuchet MS', FontStyle.italic, FontWeight.bold),
  ('Verdana', FontStyle.normal, FontWeight.normal),
  ('Verdana', FontStyle.italic, FontWeight.normal),
  ('Verdana', FontStyle.normal, FontWeight.bold),
  ('Verdana', FontStyle.italic, FontWeight.bold),
  ('Waseem', FontStyle.normal, FontWeight.normal),
  ('Webdings', FontStyle.normal, FontWeight.normal),
  ('Wingdings', FontStyle.normal, FontWeight.normal),
  ('Wingdings 2', FontStyle.normal, FontWeight.normal),
  ('Wingdings 3', FontStyle.normal, FontWeight.normal),
  ('Zapf Dingbats', FontStyle.normal, FontWeight.normal),
  ('Zapfino', FontStyle.normal, FontWeight.normal),
  ('.AppleSystemUIFont', FontStyle.normal, FontWeight.normal),
  ('Inter', FontStyle.normal, FontWeight.normal),
  ('Inter', FontStyle.normal, FontWeight.bold),
  ('Inter', FontStyle.italic, FontWeight.normal),
  ('Inter', FontStyle.italic, FontWeight.bold),
  ('System', FontStyle.normal, FontWeight.normal),
  ('System', FontStyle.normal, FontWeight.bold),
  ('System', FontStyle.italic, FontWeight.normal),
  ('System', FontStyle.italic, FontWeight.bold),
];
