part of 'gen_fonts.dart';

_add_fonts_windows(Map<String, List<(String, FontStyle, FontWeight)>> fonts) {
  fonts["windows"] = [
    ('Modern', FontStyle.normal, FontWeight.normal),
    ('Roman', FontStyle.normal, FontWeight.normal),
    ('Script', FontStyle.normal, FontWeight.normal),
    ('Marlett', FontStyle.normal, FontWeight.normal),
    ('Arial', FontStyle.normal, FontWeight.normal),
    ('Arabic Transparent', FontStyle.normal, FontWeight.normal),
    ('Arial Baltic', FontStyle.normal, FontWeight.normal),
    ('Arial CE', FontStyle.normal, FontWeight.normal),
    ('Arial CYR', FontStyle.normal, FontWeight.normal),
    ('Arial Greek', FontStyle.normal, FontWeight.normal),
    ('Arial TUR', FontStyle.normal, FontWeight.normal),
    ('Arial', FontStyle.normal, FontWeight.bold),
    ('Arabic Transparent', FontStyle.normal, FontWeight.bold),
    ('Arial Baltic', FontStyle.normal, FontWeight.bold),
    ('Arial CE', FontStyle.normal, FontWeight.bold),
    ('Arial CYR', FontStyle.normal, FontWeight.bold),
    ('Arial Greek', FontStyle.normal, FontWeight.bold),
    ('Arial TUR', FontStyle.normal, FontWeight.bold),
    ('Arial', FontStyle.italic, FontWeight.bold),
    ('Arabic Transparent', FontStyle.italic, FontWeight.bold),
    ('Arial Baltic', FontStyle.italic, FontWeight.bold),
    ('Arial CE', FontStyle.italic, FontWeight.bold),
    ('Arial CYR', FontStyle.italic, FontWeight.bold),
    ('Arial Greek', FontStyle.italic, FontWeight.bold),
    ('Arial TUR', FontStyle.italic, FontWeight.bold),
    ('Arial', FontStyle.italic, FontWeight.normal),
    ('Arabic Transparent', FontStyle.italic, FontWeight.normal),
    ('Arial Baltic', FontStyle.italic, FontWeight.normal),
    ('Arial CE', FontStyle.italic, FontWeight.normal),
    ('Arial CYR', FontStyle.italic, FontWeight.normal),
    ('Arial Greek', FontStyle.italic, FontWeight.normal),
    ('Arial TUR', FontStyle.italic, FontWeight.normal),
    ('Arial Black', FontStyle.normal, FontWeight.normal),
    ('Bahnschrift Light', FontStyle.normal, FontWeight.normal),
    ('Bahnschrift SemiLight', FontStyle.normal, FontWeight.normal),
    ('Bahnschrift', FontStyle.normal, FontWeight.normal),
    ('Bahnschrift', FontStyle.normal, FontWeight.bold),
    ('Bahnschrift SemiBold', FontStyle.normal, FontWeight.normal),
    ('Bahnschrift Light SemiCondensed', FontStyle.normal, FontWeight.normal),
    ('Bahnschrift SemiLight SemiConde', FontStyle.normal, FontWeight.normal),
    ('Bahnschrift SemiCondensed', FontStyle.normal, FontWeight.normal),
    ('Bahnschrift SemiCondensed', FontStyle.normal, FontWeight.bold),
    ('Bahnschrift SemiBold SemiConden', FontStyle.normal, FontWeight.normal),
    ('Bahnschrift Light Condensed', FontStyle.normal, FontWeight.normal),
    ('Bahnschrift SemiLight Condensed', FontStyle.normal, FontWeight.normal),
    ('Bahnschrift Condensed', FontStyle.normal, FontWeight.normal),
    ('Bahnschrift Condensed', FontStyle.normal, FontWeight.bold),
    ('Bahnschrift SemiBold Condensed', FontStyle.normal, FontWeight.normal),
    ('Calibri', FontStyle.normal, FontWeight.normal),
    ('Calibri', FontStyle.normal, FontWeight.bold),
    ('Calibri', FontStyle.italic, FontWeight.bold),
    ('Calibri', FontStyle.italic, FontWeight.normal),
    ('Calibri Light', FontStyle.normal, FontWeight.normal),
    ('Calibri Light', FontStyle.italic, FontWeight.normal),
    ('Cambria', FontStyle.normal, FontWeight.normal),
    ('Cambria', FontStyle.normal, FontWeight.bold),
    ('Cambria', FontStyle.italic, FontWeight.bold),
    ('Cambria', FontStyle.italic, FontWeight.normal),
    ('Cambria Math', FontStyle.normal, FontWeight.normal),
    ('Candara', FontStyle.normal, FontWeight.normal),
    ('Candara', FontStyle.normal, FontWeight.bold),
    ('Candara', FontStyle.italic, FontWeight.bold),
    ('Candara', FontStyle.italic, FontWeight.normal),
    ('Candara Light', FontStyle.normal, FontWeight.normal),
    ('Candara Light', FontStyle.italic, FontWeight.normal),
    ('Comic Sans MS', FontStyle.normal, FontWeight.normal),
    ('Comic Sans MS', FontStyle.normal, FontWeight.bold),
    ('Comic Sans MS', FontStyle.italic, FontWeight.bold),
    ('Comic Sans MS', FontStyle.italic, FontWeight.normal),
    ('Consolas', FontStyle.normal, FontWeight.normal),
    ('Consolas', FontStyle.normal, FontWeight.bold),
    ('Consolas', FontStyle.italic, FontWeight.bold),
    ('Consolas', FontStyle.italic, FontWeight.normal),
    ('Constantia', FontStyle.normal, FontWeight.normal),
    ('Constantia', FontStyle.normal, FontWeight.bold),
    ('Constantia', FontStyle.italic, FontWeight.bold),
    ('Constantia', FontStyle.italic, FontWeight.normal),
    ('Corbel', FontStyle.normal, FontWeight.normal),
    ('Corbel', FontStyle.normal, FontWeight.bold),
    ('Corbel', FontStyle.italic, FontWeight.bold),
    ('Corbel', FontStyle.italic, FontWeight.normal),
    ('Corbel Light', FontStyle.normal, FontWeight.normal),
    ('Corbel Light', FontStyle.italic, FontWeight.normal),
    ('Courier New', FontStyle.normal, FontWeight.normal),
    ('Courier New Baltic', FontStyle.normal, FontWeight.normal),
    ('Courier New CE', FontStyle.normal, FontWeight.normal),
    ('Courier New CYR', FontStyle.normal, FontWeight.normal),
    ('Courier New Greek', FontStyle.normal, FontWeight.normal),
    ('Courier New TUR', FontStyle.normal, FontWeight.normal),
    ('Courier New', FontStyle.normal, FontWeight.bold),
    ('Courier New Baltic', FontStyle.normal, FontWeight.bold),
    ('Courier New CE', FontStyle.normal, FontWeight.bold),
    ('Courier New CYR', FontStyle.normal, FontWeight.bold),
    ('Courier New Greek', FontStyle.normal, FontWeight.bold),
    ('Courier New TUR', FontStyle.normal, FontWeight.bold),
    ('Courier New', FontStyle.italic, FontWeight.bold),
    ('Courier New Baltic', FontStyle.italic, FontWeight.bold),
    ('Courier New CE', FontStyle.italic, FontWeight.bold),
    ('Courier New CYR', FontStyle.italic, FontWeight.bold),
    ('Courier New Greek', FontStyle.italic, FontWeight.bold),
    ('Courier New TUR', FontStyle.italic, FontWeight.bold),
    ('Courier New', FontStyle.italic, FontWeight.normal),
    ('Courier New Baltic', FontStyle.italic, FontWeight.normal),
    ('Courier New CE', FontStyle.italic, FontWeight.normal),
    ('Courier New CYR', FontStyle.italic, FontWeight.normal),
    ('Courier New Greek', FontStyle.italic, FontWeight.normal),
    ('Courier New TUR', FontStyle.italic, FontWeight.normal),
    ('Ebrima', FontStyle.normal, FontWeight.normal),
    ('Ebrima', FontStyle.normal, FontWeight.bold),
    ('Franklin Gothic Medium', FontStyle.normal, FontWeight.normal),
    ('Franklin Gothic Medium', FontStyle.italic, FontWeight.normal),
    ('Gabriola', FontStyle.normal, FontWeight.normal),
    ('Gadugi', FontStyle.normal, FontWeight.normal),
    ('Gadugi', FontStyle.normal, FontWeight.bold),
    ('Georgia', FontStyle.normal, FontWeight.normal),
    ('Georgia', FontStyle.normal, FontWeight.bold),
    ('Georgia', FontStyle.italic, FontWeight.bold),
    ('Georgia', FontStyle.italic, FontWeight.normal),
    ('Impact', FontStyle.normal, FontWeight.normal),
    ('Ink Free', FontStyle.normal, FontWeight.normal),
    ('Javanese Text', FontStyle.normal, FontWeight.normal),
    ('Leelawadee UI', FontStyle.normal, FontWeight.normal),
    ('Leelawadee UI', FontStyle.normal, FontWeight.bold),
    ('Leelawadee UI Semilight', FontStyle.normal, FontWeight.normal),
    ('Lucida Console', FontStyle.normal, FontWeight.normal),
    ('Lucida Sans Unicode', FontStyle.normal, FontWeight.normal),
    ('Malgun Gothic', FontStyle.normal, FontWeight.normal),
    ('Malgun Gothic', FontStyle.normal, FontWeight.bold),
    ('@Malgun Gothic', FontStyle.normal, FontWeight.normal),
    ('@Malgun Gothic', FontStyle.normal, FontWeight.bold),
    ('Malgun Gothic Semilight', FontStyle.normal, FontWeight.normal),
    ('@Malgun Gothic Semilight', FontStyle.normal, FontWeight.normal),
    ('Microsoft Himalaya', FontStyle.normal, FontWeight.normal),
    ('Microsoft JhengHei', FontStyle.normal, FontWeight.normal),
    ('Microsoft JhengHei', FontStyle.normal, FontWeight.bold),
    ('@Microsoft JhengHei', FontStyle.normal, FontWeight.normal),
    ('@Microsoft JhengHei', FontStyle.normal, FontWeight.bold),
    ('Microsoft JhengHei UI', FontStyle.normal, FontWeight.normal),
    ('Microsoft JhengHei UI', FontStyle.normal, FontWeight.bold),
    ('@Microsoft JhengHei UI', FontStyle.normal, FontWeight.normal),
    ('@Microsoft JhengHei UI', FontStyle.normal, FontWeight.bold),
    ('Microsoft JhengHei Light', FontStyle.normal, FontWeight.normal),
    ('@Microsoft JhengHei Light', FontStyle.normal, FontWeight.normal),
    ('Microsoft JhengHei UI Light', FontStyle.normal, FontWeight.normal),
    ('@Microsoft JhengHei UI Light', FontStyle.normal, FontWeight.normal),
    ('Microsoft New Tai Lue', FontStyle.normal, FontWeight.normal),
    ('Microsoft New Tai Lue', FontStyle.normal, FontWeight.bold),
    ('Microsoft PhagsPa', FontStyle.normal, FontWeight.normal),
    ('Microsoft PhagsPa', FontStyle.normal, FontWeight.bold),
    ('Microsoft Sans Serif', FontStyle.normal, FontWeight.normal),
    ('Microsoft Tai Le', FontStyle.normal, FontWeight.normal),
    ('Microsoft Tai Le', FontStyle.normal, FontWeight.bold),
    ('Microsoft YaHei', FontStyle.normal, FontWeight.normal),
    ('Microsoft YaHei', FontStyle.normal, FontWeight.bold),
    ('@Microsoft YaHei', FontStyle.normal, FontWeight.normal),
    ('@Microsoft YaHei', FontStyle.normal, FontWeight.bold),
    ('Microsoft YaHei UI', FontStyle.normal, FontWeight.normal),
    ('Microsoft YaHei UI', FontStyle.normal, FontWeight.bold),
    ('@Microsoft YaHei UI', FontStyle.normal, FontWeight.normal),
    ('@Microsoft YaHei UI', FontStyle.normal, FontWeight.bold),
    ('Microsoft YaHei Light', FontStyle.normal, FontWeight.normal),
    ('@Microsoft YaHei Light', FontStyle.normal, FontWeight.normal),
    ('Microsoft YaHei UI Light', FontStyle.normal, FontWeight.normal),
    ('@Microsoft YaHei UI Light', FontStyle.normal, FontWeight.normal),
    ('Microsoft Yi Baiti', FontStyle.normal, FontWeight.normal),
    ('MingLiU-ExtB', FontStyle.normal, FontWeight.normal),
    ('@MingLiU-ExtB', FontStyle.normal, FontWeight.normal),
    ('PMingLiU-ExtB', FontStyle.normal, FontWeight.normal),
    ('@PMingLiU-ExtB', FontStyle.normal, FontWeight.normal),
    ('MingLiU_HKSCS-ExtB', FontStyle.normal, FontWeight.normal),
    ('@MingLiU_HKSCS-ExtB', FontStyle.normal, FontWeight.normal),
    ('MingLiU_MSCS-ExtB', FontStyle.normal, FontWeight.normal),
    ('@MingLiU_MSCS-ExtB', FontStyle.normal, FontWeight.normal),
    ('Mongolian Baiti', FontStyle.normal, FontWeight.normal),
    ('MS Gothic', FontStyle.normal, FontWeight.normal),
    ('@MS Gothic', FontStyle.normal, FontWeight.normal),
    ('MS UI Gothic', FontStyle.normal, FontWeight.normal),
    ('@MS UI Gothic', FontStyle.normal, FontWeight.normal),
    ('MS PGothic', FontStyle.normal, FontWeight.normal),
    ('@MS PGothic', FontStyle.normal, FontWeight.normal),
    ('MV Boli', FontStyle.normal, FontWeight.normal),
    ('Myanmar Text', FontStyle.normal, FontWeight.normal),
    ('Myanmar Text', FontStyle.normal, FontWeight.bold),
    ('Nirmala UI', FontStyle.normal, FontWeight.normal),
    ('Nirmala UI', FontStyle.normal, FontWeight.bold),
    ('Nirmala UI Semilight', FontStyle.normal, FontWeight.normal),
    ('Nirmala Text', FontStyle.normal, FontWeight.normal),
    ('Nirmala Text', FontStyle.normal, FontWeight.bold),
    ('Nirmala Text Semilight', FontStyle.normal, FontWeight.normal),
    ('Palatino Linotype', FontStyle.normal, FontWeight.normal),
    ('Palatino Linotype', FontStyle.normal, FontWeight.bold),
    ('Palatino Linotype', FontStyle.italic, FontWeight.bold),
    ('Palatino Linotype', FontStyle.italic, FontWeight.normal),
    ('Sans Serif Collection', FontStyle.normal, FontWeight.normal),
    ('Segoe Fluent Icons', FontStyle.normal, FontWeight.normal),
    ('Segoe MDL2 Assets', FontStyle.normal, FontWeight.normal),
    ('Segoe Print', FontStyle.normal, FontWeight.normal),
    ('Segoe Print', FontStyle.normal, FontWeight.bold),
    ('Segoe Script', FontStyle.normal, FontWeight.normal),
    ('Segoe Script', FontStyle.normal, FontWeight.bold),
    ('Segoe UI', FontStyle.normal, FontWeight.normal),
    ('Segoe UI', FontStyle.normal, FontWeight.bold),
    ('Segoe UI', FontStyle.italic, FontWeight.bold),
    ('Segoe UI', FontStyle.italic, FontWeight.normal),
    ('Segoe UI Black', FontStyle.normal, FontWeight.normal),
    ('Segoe UI Black', FontStyle.italic, FontWeight.normal),
    ('Segoe UI Emoji', FontStyle.normal, FontWeight.normal),
    ('Segoe UI Historic', FontStyle.normal, FontWeight.normal),
    ('Segoe UI Light', FontStyle.normal, FontWeight.normal),
    ('Segoe UI Light', FontStyle.italic, FontWeight.normal),
    ('Segoe UI Semibold', FontStyle.normal, FontWeight.normal),
    ('Segoe UI Semibold', FontStyle.italic, FontWeight.normal),
    ('Segoe UI Semilight', FontStyle.normal, FontWeight.normal),
    ('Segoe UI Semilight', FontStyle.italic, FontWeight.normal),
    ('Segoe UI Symbol', FontStyle.normal, FontWeight.normal),
    ('Segoe UI Variable Small Light', FontStyle.normal, FontWeight.normal),
    ('Segoe UI Variable Small Semilig', FontStyle.normal, FontWeight.normal),
    ('Segoe UI Variable Small', FontStyle.normal, FontWeight.normal),
    ('Segoe UI Variable Small', FontStyle.normal, FontWeight.bold),
    ('Segoe UI Variable Small Semibol', FontStyle.normal, FontWeight.normal),
    ('Segoe UI Variable Text Light', FontStyle.normal, FontWeight.normal),
    ('Segoe UI Variable Text Semiligh', FontStyle.normal, FontWeight.normal),
    ('Segoe UI Variable Text', FontStyle.normal, FontWeight.normal),
    ('Segoe UI Variable Text', FontStyle.normal, FontWeight.bold),
    ('Segoe UI Variable Text Semibold', FontStyle.normal, FontWeight.normal),
    ('Segoe UI Variable Display Light', FontStyle.normal, FontWeight.normal),
    ('Segoe UI Variable Display Semil', FontStyle.normal, FontWeight.normal),
    ('Segoe UI Variable Display', FontStyle.normal, FontWeight.normal),
    ('Segoe UI Variable Display', FontStyle.normal, FontWeight.bold),
    ('Segoe UI Variable Display Semib', FontStyle.normal, FontWeight.normal),
    ('SimSun', FontStyle.normal, FontWeight.normal),
    ('@SimSun', FontStyle.normal, FontWeight.normal),
    ('NSimSun', FontStyle.normal, FontWeight.normal),
    ('@NSimSun', FontStyle.normal, FontWeight.normal),
    ('SimSun-ExtB', FontStyle.normal, FontWeight.normal),
    ('@SimSun-ExtB', FontStyle.normal, FontWeight.normal),
    ('Sitka Small', FontStyle.normal, FontWeight.normal),
    ('Sitka Small', FontStyle.normal, FontWeight.bold),
    ('Sitka Small', FontStyle.italic, FontWeight.normal),
    ('Sitka Small', FontStyle.italic, FontWeight.bold),
    ('Sitka Small Semibold', FontStyle.normal, FontWeight.normal),
    ('Sitka Small Semibold', FontStyle.italic, FontWeight.normal),
    ('Sitka Text', FontStyle.normal, FontWeight.normal),
    ('Sitka Text', FontStyle.normal, FontWeight.bold),
    ('Sitka Text', FontStyle.italic, FontWeight.normal),
    ('Sitka Text', FontStyle.italic, FontWeight.bold),
    ('Sitka Text Semibold', FontStyle.normal, FontWeight.normal),
    ('Sitka Text Semibold', FontStyle.italic, FontWeight.normal),
    ('Sitka Subheading', FontStyle.normal, FontWeight.normal),
    ('Sitka Subheading', FontStyle.normal, FontWeight.bold),
    ('Sitka Subheading', FontStyle.italic, FontWeight.normal),
    ('Sitka Subheading', FontStyle.italic, FontWeight.bold),
    ('Sitka Subheading Semibold', FontStyle.normal, FontWeight.normal),
    ('Sitka Subheading Semibold', FontStyle.italic, FontWeight.normal),
    ('Sitka Heading', FontStyle.normal, FontWeight.normal),
    ('Sitka Heading', FontStyle.normal, FontWeight.bold),
    ('Sitka Heading', FontStyle.italic, FontWeight.normal),
    ('Sitka Heading', FontStyle.italic, FontWeight.bold),
    ('Sitka Heading Semibold', FontStyle.normal, FontWeight.normal),
    ('Sitka Heading Semibold', FontStyle.italic, FontWeight.normal),
    ('Sitka Display', FontStyle.normal, FontWeight.normal),
    ('Sitka Display', FontStyle.normal, FontWeight.bold),
    ('Sitka Display', FontStyle.italic, FontWeight.normal),
    ('Sitka Display', FontStyle.italic, FontWeight.bold),
    ('Sitka Display Semibold', FontStyle.normal, FontWeight.normal),
    ('Sitka Display Semibold', FontStyle.italic, FontWeight.normal),
    ('Sitka Banner', FontStyle.normal, FontWeight.normal),
    ('Sitka Banner', FontStyle.normal, FontWeight.bold),
    ('Sitka Banner', FontStyle.italic, FontWeight.normal),
    ('Sitka Banner', FontStyle.italic, FontWeight.bold),
    ('Sitka Banner Semibold', FontStyle.normal, FontWeight.normal),
    ('Sitka Banner Semibold', FontStyle.italic, FontWeight.normal),
    ('Sylfaen', FontStyle.normal, FontWeight.normal),
    ('Symbol', FontStyle.normal, FontWeight.normal),
    ('Tahoma', FontStyle.normal, FontWeight.normal),
    ('Tahoma', FontStyle.normal, FontWeight.bold),
    ('Times New Roman', FontStyle.normal, FontWeight.normal),
    ('Times New Roman Baltic', FontStyle.normal, FontWeight.normal),
    ('Times New Roman CE', FontStyle.normal, FontWeight.normal),
    ('Times New Roman CYR', FontStyle.normal, FontWeight.normal),
    ('Times New Roman Greek', FontStyle.normal, FontWeight.normal),
    ('Times New Roman TUR', FontStyle.normal, FontWeight.normal),
    ('Times New Roman', FontStyle.normal, FontWeight.bold),
    ('Times New Roman Baltic', FontStyle.normal, FontWeight.bold),
    ('Times New Roman CE', FontStyle.normal, FontWeight.bold),
    ('Times New Roman CYR', FontStyle.normal, FontWeight.bold),
    ('Times New Roman Greek', FontStyle.normal, FontWeight.bold),
    ('Times New Roman TUR', FontStyle.normal, FontWeight.bold),
    ('Times New Roman', FontStyle.italic, FontWeight.bold),
    ('Times New Roman Baltic', FontStyle.italic, FontWeight.bold),
    ('Times New Roman CE', FontStyle.italic, FontWeight.bold),
    ('Times New Roman CYR', FontStyle.italic, FontWeight.bold),
    ('Times New Roman Greek', FontStyle.italic, FontWeight.bold),
    ('Times New Roman TUR', FontStyle.italic, FontWeight.bold),
    ('Times New Roman', FontStyle.italic, FontWeight.normal),
    ('Times New Roman Baltic', FontStyle.italic, FontWeight.normal),
    ('Times New Roman CE', FontStyle.italic, FontWeight.normal),
    ('Times New Roman CYR', FontStyle.italic, FontWeight.normal),
    ('Times New Roman Greek', FontStyle.italic, FontWeight.normal),
    ('Times New Roman TUR', FontStyle.italic, FontWeight.normal),
    ('Trebuchet MS', FontStyle.normal, FontWeight.normal),
    ('Trebuchet MS', FontStyle.normal, FontWeight.bold),
    ('Trebuchet MS', FontStyle.italic, FontWeight.bold),
    ('Trebuchet MS', FontStyle.italic, FontWeight.normal),
    ('Verdana', FontStyle.normal, FontWeight.normal),
    ('Verdana', FontStyle.normal, FontWeight.bold),
    ('Verdana', FontStyle.italic, FontWeight.bold),
    ('Verdana', FontStyle.italic, FontWeight.normal),
    ('Webdings', FontStyle.normal, FontWeight.normal),
    ('Wingdings', FontStyle.normal, FontWeight.normal),
    ('Yu Gothic', FontStyle.normal, FontWeight.normal),
    ('Yu Gothic', FontStyle.normal, FontWeight.bold),
    ('@Yu Gothic', FontStyle.normal, FontWeight.normal),
    ('@Yu Gothic', FontStyle.normal, FontWeight.bold),
    ('Yu Gothic UI', FontStyle.normal, FontWeight.normal),
    ('Yu Gothic UI', FontStyle.normal, FontWeight.bold),
    ('@Yu Gothic UI', FontStyle.normal, FontWeight.normal),
    ('@Yu Gothic UI', FontStyle.normal, FontWeight.bold),
    ('Yu Gothic UI Semibold', FontStyle.normal, FontWeight.normal),
    ('@Yu Gothic UI Semibold', FontStyle.normal, FontWeight.normal),
    ('Yu Gothic Light', FontStyle.normal, FontWeight.normal),
    ('@Yu Gothic Light', FontStyle.normal, FontWeight.normal),
    ('Yu Gothic UI Light', FontStyle.normal, FontWeight.normal),
    ('@Yu Gothic UI Light', FontStyle.normal, FontWeight.normal),
    ('Yu Gothic Medium', FontStyle.normal, FontWeight.normal),
    ('@Yu Gothic Medium', FontStyle.normal, FontWeight.normal),
    ('Yu Gothic UI Semilight', FontStyle.normal, FontWeight.normal),
    ('@Yu Gothic UI Semilight', FontStyle.normal, FontWeight.normal),
    ('Cascadia Code ExtraLight', FontStyle.normal, FontWeight.normal),
    ('Cascadia Code ExtraLight', FontStyle.italic, FontWeight.normal),
    ('Cascadia Code Light', FontStyle.normal, FontWeight.normal),
    ('Cascadia Code Light', FontStyle.italic, FontWeight.normal),
    ('Cascadia Code SemiLight', FontStyle.normal, FontWeight.normal),
    ('Cascadia Code SemiLight', FontStyle.italic, FontWeight.normal),
    ('Cascadia Code', FontStyle.normal, FontWeight.normal),
    ('Cascadia Code', FontStyle.normal, FontWeight.bold),
    ('Cascadia Code', FontStyle.italic, FontWeight.normal),
    ('Cascadia Code', FontStyle.italic, FontWeight.bold),
    ('Cascadia Code SemiBold', FontStyle.normal, FontWeight.normal),
    ('Cascadia Code SemiBold', FontStyle.italic, FontWeight.normal),
    ('Cascadia Mono ExtraLight', FontStyle.normal, FontWeight.normal),
    ('Cascadia Mono ExtraLight', FontStyle.italic, FontWeight.normal),
    ('Cascadia Mono Light', FontStyle.normal, FontWeight.normal),
    ('Cascadia Mono Light', FontStyle.italic, FontWeight.normal),
    ('Cascadia Mono SemiLight', FontStyle.normal, FontWeight.normal),
    ('Cascadia Mono SemiLight', FontStyle.italic, FontWeight.normal),
    ('Cascadia Mono', FontStyle.normal, FontWeight.normal),
    ('Cascadia Mono', FontStyle.normal, FontWeight.bold),
    ('Cascadia Mono', FontStyle.italic, FontWeight.normal),
    ('Cascadia Mono', FontStyle.italic, FontWeight.bold),
    ('Cascadia Mono SemiBold', FontStyle.normal, FontWeight.normal),
    ('Cascadia Mono SemiBold', FontStyle.italic, FontWeight.normal),
    ('Inter', FontStyle.normal, FontWeight.normal),
    ('Inter', FontStyle.normal, FontWeight.bold),
    ('Inter', FontStyle.italic, FontWeight.normal),
    ('Inter', FontStyle.italic, FontWeight.bold),
    ('System', FontStyle.normal, FontWeight.normal),
    ('System', FontStyle.normal, FontWeight.bold),
    ('System', FontStyle.italic, FontWeight.normal),
    ('System', FontStyle.italic, FontWeight.bold),
  ];
}
