import 'dart:io';
import 'package:flutter/material.dart';
import 'package:swtflutter/src/theme/theme.dart';

/// Generates dev/equo/swt/size/CanvasTheme.java from the app's own default dark ColorScheme —
/// surface, the color CanvasThemeExtension.backgroundColor resolves to for a genuinely
/// Dart-rendered Canvas (canvas_theme_settings.dart's _getCanvasTheme), and onSurface, the
/// foreground meant to be legible on it.
///
/// Unlike the other measure_*.dart scripts, there's no widget to render or TextStyle to measure —
/// a Canvas draws no text of its own — so this reads the ColorScheme directly instead of going
/// through WidgetMeasurer/MeasurementApp, and exits immediately after writing the file.
void main() {
  WidgetsFlutterBinding.ensureInitialized();
  writeCanvasThemeFile();
  exit(0);
}

int _toByte(double component) => (component * 255.0).round().clamp(0, 255);

void writeCanvasThemeFile() {
  final scheme = createDarkColorScheme();
  final surface = scheme.surface;
  final red = _toByte(surface.r);
  final green = _toByte(surface.g);
  final blue = _toByte(surface.b);
  final onSurface = scheme.onSurface;
  final onRed = _toByte(onSurface.r);
  final onGreen = _toByte(onSurface.g);
  final onBlue = _toByte(onSurface.b);

  final buffer = StringBuffer();
  buffer.writeln('package dev.equo.swt.size;');
  buffer.writeln();
  buffer.writeln('/**');
  buffer.writeln(
    ' * Mirrors the app\'s default dark {@code ColorScheme.surface} and {@code onSurface} —',
  );
  buffer.writeln(
    ' * {@code flutter-lib/lib/src/theme/theme.dart}, {@code createDarkColorScheme()} — the same color',
  );
  buffer.writeln(
    ' * {@code CanvasThemeExtension.backgroundColor} resolves to for a genuinely Dart-rendered Canvas',
  );
  buffer.writeln(
    ' * ({@code canvas_theme_settings.dart}\'s {@code _getCanvasTheme}).',
  );
  buffer.writeln(' *');
  buffer.writeln(
    ' * <p>Generated by {@code flutter-lib/tool/measure_canvas.dart} — unlike {@link ButtonTheme}',
  );
  buffer.writeln(
    ' * and its siblings, which measure live {@code TextStyle} font metrics, this reads the',
  );
  buffer.writeln(
    ' * {@code ColorScheme} directly (a Canvas draws no text of its own to measure).',
  );
  buffer.writeln(' *');
  buffer.writeln(
    ' * <p>There is no live Dart-to-Java channel a synchronous Java call like',
  );
  buffer.writeln(
    ' * {@code Display.getSystemColor()} can use to read this at call time — colors only flow',
  );
  buffer.writeln(
    ' * Java-config to Dart-theme, never the other way, and Java may run before Flutter has even',
  );
  buffer.writeln(
    ' * connected. So the value is mirrored here as a literal, regenerated by re-running this script',
  );
  buffer.writeln(
    ' * whenever {@code theme.dart}\'s dark surface colors change.',
  );
  buffer.writeln(' *');
  buffer.writeln(
    ' * <p>The two are a pair: a system foreground color must be read from the same scheme as the',
  );
  buffer.writeln(
    ' * background it is drawn on, or an application that sets neither inherits one of each theme.',
  );
  buffer.writeln(' */');
  buffer.writeln('public record CanvasTheme(int red, int green, int blue) {');
  buffer.writeln('    public static CanvasTheme getDarkSurface() {');
  buffer.writeln('        return new CanvasTheme($red, $green, $blue);');
  buffer.writeln('    }');
  buffer.writeln();
  buffer.writeln('    public static CanvasTheme getDarkOnSurface() {');
  buffer.writeln('        return new CanvasTheme($onRed, $onGreen, $onBlue);');
  buffer.writeln('    }');
  buffer.writeln('}');

  final file = File(
    '../swt_native/src/main/java/dev/equo/swt/size/CanvasTheme.java',
  );
  file.writeAsStringSync(buffer.toString());
  print('Generated: ${file.path}');
}
