package dev.equo.swt.size;

/**
 * Mirrors the app's default dark {@code ColorScheme.surface} —
 * {@code flutter-lib/lib/src/theme/theme.dart}, {@code createDarkColorScheme()} — the same color
 * {@code CanvasThemeExtension.backgroundColor} resolves to for a genuinely Dart-rendered Canvas
 * ({@code canvas_theme_settings.dart}'s {@code _getCanvasTheme}).
 *
 * <p>Generated by {@code flutter-lib/tool/measure_canvas.dart} — unlike {@link ButtonTheme}
 * and its siblings, which measure live {@code TextStyle} font metrics, this reads the
 * {@code ColorScheme} directly (a Canvas draws no text of its own to measure).
 *
 * <p>There is no live Dart-to-Java channel a synchronous Java call like
 * {@code Display.getSystemColor()} can use to read this at call time — colors only flow
 * Java-config to Dart-theme, never the other way, and Java may run before Flutter has even
 * connected. So the value is mirrored here as a literal, regenerated by re-running this script
 * whenever {@code theme.dart}'s dark surface color changes.
 */
public record CanvasTheme(int red, int green, int blue) {
    public static CanvasTheme getDarkSurface() {
        return new CanvasTheme(31, 41, 55);
    }
}
