package dev.equo.swt.size;

/**
 * Mirrors the app's default dark {@code ColorScheme.surface} and {@code onSurface} —
 * {@code flutter-lib/lib/src/theme/theme.dart}, {@code createDarkColorScheme()} — the same color
 * {@code CanvasThemeExtension.backgroundColor} resolves to for a genuinely Dart-rendered Canvas
 * ({@code canvas_theme_settings.dart}'s {@code _getCanvasTheme}).
 *
 * <p>Generated by {@code flutter-lib/tool/measure_canvas.dart} — unlike {@link ButtonTheme}
 * and its siblings, which measure live {@code TextStyle} font metrics, this reads the
 * {@code ColorScheme} directly (a Canvas draws no text of its own to measure).
 *
 * <p>There is no live Dart-to-Java channel a synchronous Java call like
 * {@code Display.getSystemColor()} can use to read this at call time — colors only flow
 * Java-config to Dart-theme, never the other way, and Java may run before Flutter has even
 * connected. So the value is mirrored here as a literal, regenerated by re-running this script
 * whenever {@code theme.dart}'s dark surface colors change.
 *
 * <p>The two are a pair: a system foreground color must be read from the same scheme as the
 * background it is drawn on, or an application that sets neither inherits one of each theme.
 */
public final class CanvasTheme {
    private final int red;
    private final int green;
    private final int blue;

    public CanvasTheme(int red, int green, int blue) {
        this.red = red;
        this.green = green;
        this.blue = blue;
    }

    public int red() { return red; }
    public int green() { return green; }
    public int blue() { return blue; }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof CanvasTheme)) return false;
        CanvasTheme other = (CanvasTheme) o;
        return red == other.red
            && green == other.green
            && blue == other.blue;
    }

    @Override
    public int hashCode() { return java.util.Objects.hash(red, green, blue); }

    @Override
    public String toString() { return "CanvasTheme[red=" + red + ", green=" + green + ", blue=" + blue + "]"; }

    public static CanvasTheme getDarkSurface() {
        return new CanvasTheme(31, 41, 55);
    }

    public static CanvasTheme getDarkOnSurface() {
        return new CanvasTheme(249, 250, 251);
    }
}
